<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_From_white-ro form-control pointer ng_bc7ee6</name>
   <tag></tag>
   <elementGuidId>63587f1d-aa14-4095-85bc-3344dd06921a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.white-ro.form-control.pointer.ng-pristine.ng-untouched.ng-valid.ng-empty.ng-valid-datetime</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0f50ff24-e59c-49af-857b-72471b72aaef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2583ac80-a8d3-47a8-8b4e-dd05346fc5f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>white-ro form-control pointer ng-pristine ng-untouched ng-valid ng-empty ng-valid-datetime</value>
      <webElementGuid>aeb10460-fbea-408c-830f-2a32dbb0723e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datetime-picker</name>
      <type>Main</type>
      <value>MM/dd yyyy, hh:mm a</value>
      <webElementGuid>ed722988-a96f-4881-a3c2-9d0a91ffb129</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>is-open</name>
      <type>Main</type>
      <value>utils.pickerStartOpened</value>
      <webElementGuid>b8239908-0f98-497c-b35f-123ab55ca730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>uib-timepicker-options</name>
      <type>Main</type>
      <value>utils.pickerDateStart</value>
      <webElementGuid>31d5dba6-224f-4d5f-b297-d131532353f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>utils.pickerStartOpened = !utils.pickerStartOpened</value>
      <webElementGuid>85dccfa9-527d-4c6a-b6cb-03a98f4a0a5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>utils.start</value>
      <webElementGuid>b7515390-b1c9-446d-8ff3-c8cc0fdbd2de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>073528c9-d422-48ed-8558-2c2454beafdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-js&quot;]/body[1]/div[@class=&quot;container-fluid block-height-min&quot;]/div[@class=&quot;row rowm0&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;tab-content eo-dashboard&quot;]/div[@class=&quot;tab-pane active&quot;]/div[1]/div[@class=&quot;row row-space rowm0&quot;]/div[@class=&quot;tickets-settings-form col-xs-12 col-sm-4&quot;]/div[@class=&quot;input-group date-time-control col-md-8 col-sm-10&quot;]/input[@class=&quot;white-ro form-control pointer ng-pristine ng-untouched ng-valid ng-empty ng-valid-datetime&quot;]</value>
      <webElementGuid>a24c81f6-ac38-4f22-9109-e10a8a3b483d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='text']</value>
      <webElementGuid>550c90b5-5f4f-41f2-9bd7-13ad61512b31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>718505f5-7bc4-4d00-847c-58ef292e3230</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>a32f5e99-affd-47c7-bfc5-74bb781d1bd4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
