<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_edit_form-control input-sm ng-pristin_1ea9ba</name>
   <tag></tag>
   <elementGuidId>aca506e1-bea8-4921-aef6-bacc4038df2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.form-control.input-sm.ng-pristine.ng-untouched.ng-valid.ng-empty.w-sm.pull-right</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[11]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4a60312c-c58c-4b27-8afc-1cb868827ca4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>elType !== 'select' &amp;&amp; elType !== 'checkbox'</value>
      <webElementGuid>3617d76e-eb9e-4f79-8a6e-373c51ca902f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>338709c4-52b2-4314-991d-c52cc79eeab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>utils.val</value>
      <webElementGuid>7dbc6507-5ad7-449b-8886-a592e46f021a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-sm ng-pristine ng-untouched ng-valid ng-empty w-sm pull-right</value>
      <webElementGuid>d5bc454f-7143-4383-9be6-5c70d3113bc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'w-sm pull-right': priceType(), 'w-lg': !priceType()}</value>
      <webElementGuid>d2bd65d0-77b9-4c92-a025-3e33ca0b87f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>00.00</value>
      <webElementGuid>5b615b7c-8f4c-4cbd-a297-09d6acbcd0a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-show</name>
      <type>Main</type>
      <value>isEditing</value>
      <webElementGuid>4ec56dc7-9bbb-4105-9e9c-02abac5d4e2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>onChange()</value>
      <webElementGuid>efb18b4a-ef24-44b4-a854-7f42e7c5f633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-js&quot;]/body[1]/div[@class=&quot;container-fluid block-height-min&quot;]/div[@class=&quot;row rowm0&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;tab-content eo-dashboard&quot;]/div[@class=&quot;tab-pane active&quot;]/div[1]/tickets-table[1]/div[@class=&quot;row row-mb--20&quot;]/div[@class=&quot;col-md-12&quot;]/table[@class=&quot;table tickets-table&quot;]/tbody[1]/tr[1]/td[@class=&quot;text-right&quot;]/div[@class=&quot;editable-cell block-lg&quot;]/input[@class=&quot;form-control input-sm ng-pristine ng-untouched ng-valid ng-empty w-sm pull-right&quot;]</value>
      <webElementGuid>46609f00-cbe2-43d7-bf41-2fa480e8ad27</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[11]</value>
      <webElementGuid>e479717c-ec0a-4b0e-be15-d1f7738bd682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[10]/div/input</value>
      <webElementGuid>e86ec3d0-e7f1-44fc-84ec-367d96e76cdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = '00.00']</value>
      <webElementGuid>9b494d43-c5f9-40a7-9fa6-2120328fe7ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
