<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_edit_form-control input-sm ng-pristin_1ea9ba_1</name>
   <tag></tag>
   <elementGuidId>876d71d9-31c8-4856-a30e-0d1b427f2e54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(2) > td.text-right > div.editable-cell.block-lg > input.form-control.input-sm.ng-pristine.ng-untouched.ng-valid.ng-empty.w-sm.pull-right</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[15]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b636e0b5-bada-4fd8-a353-6112682518d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>elType !== 'select' &amp;&amp; elType !== 'checkbox'</value>
      <webElementGuid>93ad2f5b-7537-457a-95ad-f78d3094a8d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ab877b3c-e526-4ed1-9b7d-41a17f843699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>utils.val</value>
      <webElementGuid>703d2006-4461-43a4-b93b-d5c66f4b6ce5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-sm ng-pristine ng-untouched ng-valid ng-empty w-sm pull-right</value>
      <webElementGuid>e44fc41b-6e77-4836-b4b7-42be6f28f835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'w-sm pull-right': priceType(), 'w-lg': !priceType()}</value>
      <webElementGuid>4a83b2ff-fb1f-410d-be48-70b921eed7b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>00.00</value>
      <webElementGuid>47b55260-26d2-4e1d-a285-cd527d5cc1a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-show</name>
      <type>Main</type>
      <value>isEditing</value>
      <webElementGuid>b17922e1-500b-46b5-939b-a04fdd6e6f29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>onChange()</value>
      <webElementGuid>0b67b9e8-2f5e-44e0-bf5d-a74e16db93bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-js&quot;]/body[1]/div[@class=&quot;container-fluid block-height-min&quot;]/div[@class=&quot;row rowm0&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;tab-content eo-dashboard&quot;]/div[@class=&quot;tab-pane active&quot;]/div[1]/tickets-table[1]/div[@class=&quot;row row-mb--20&quot;]/div[@class=&quot;col-md-12&quot;]/table[@class=&quot;table tickets-table&quot;]/tbody[1]/tr[2]/td[@class=&quot;text-right&quot;]/div[@class=&quot;editable-cell block-lg&quot;]/input[@class=&quot;form-control input-sm ng-pristine ng-untouched ng-valid ng-empty w-sm pull-right&quot;]</value>
      <webElementGuid>efa56866-15f5-4d64-a552-9d5134538430</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[15]</value>
      <webElementGuid>730960bc-3aeb-43ff-bc6b-6ffcc217d3aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[10]/div/input</value>
      <webElementGuid>60641f2a-157f-48ed-bdc7-c938506c187c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = '00.00']</value>
      <webElementGuid>e583a9f7-b8b0-4285-81ed-872b449ca9ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
