<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_1,000.00</name>
   <tag></tag>
   <elementGuidId>c2cf4d77-8c2a-458d-9cd2-2caf237fcbd4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.ml7 > b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='accordiongroup-1085-5060-tab']/h4/a/span/payment-info-accord-heading/span/span/b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;#16822838 - CARD (paid) 04/04 1:18pm $1,000.00&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>d1b96517-ef9e-4bef-b377-557544ddaaff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$1,000.00</value>
      <webElementGuid>4e393020-c7b3-4429-b9dc-9f80c3e48342</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accordiongroup-1085-5060-tab&quot;)/h4[@class=&quot;panel-title&quot;]/a[@class=&quot;accordion-toggle&quot;]/span[1]/payment-info-accord-heading[1]/span[@class=&quot;text-success&quot;]/span[@class=&quot;ml7&quot;]/b[1]</value>
      <webElementGuid>6d62f7b9-1678-4f04-998f-3a74a0dae358</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordiongroup-1085-5060-tab']/h4/a/span/payment-info-accord-heading/span/span/b</value>
      <webElementGuid>602fc2df-de97-4517-8551-e7b45f23b889</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CARD (paid)'])[1]/following::b[1]</value>
      <webElementGuid>0618655c-b870-4fde-9058-b3d02b23c4ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/following::b[1]</value>
      <webElementGuid>c4f6dd67-4328-42cf-9dd3-3c5a4eb939b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created:'])[1]/preceding::b[1]</value>
      <webElementGuid>981cff66-c3cd-41ab-913c-8a60cd932772</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payer:'])[1]/preceding::b[1]</value>
      <webElementGuid>122b8ce7-2dfa-451d-89b1-08935d46485a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$1,000.00']/parent::*</value>
      <webElementGuid>f857790a-aab8-466a-914b-05acedf27a7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/b</value>
      <webElementGuid>fb5c2978-e496-4b94-b43f-bcf174a68b44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = '$1,000.00' or . = '$1,000.00')]</value>
      <webElementGuid>a9852444-b858-49ac-b8e0-9d4a58c74cc5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
