<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Pay 2,000.00</name>
   <tag></tag>
   <elementGuidId>ff1b4799-bb4c-42e6-a6c2-b922dc0be6ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>79eb83fd-79a4-4399-a256-3953cea4fd63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn</value>
      <webElementGuid>43a2fb8d-6af7-42f3-a277-d2fb452de99f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-style</name>
      <type>Main</type>
      <value>$ctrl.isCardSelected() &amp;&amp; {'margin-top': 0}</value>
      <webElementGuid>4348d411-2f59-41cc-90b1-c33bcf35fe43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>98e169e3-aa99-4cd0-9a41-6c907eb479ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>$ctrl.submit()</value>
      <webElementGuid>f194e43c-8f43-47e7-bad6-8d8735cace07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>!$ctrl.submitAllowed()</value>
      <webElementGuid>6b13a405-679c-4dbe-988b-1429855279b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pay $2,000.00</value>
      <webElementGuid>e37bee61-f277-4f1c-8baf-e0f073c54d14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment-form&quot;)/button[@class=&quot;btn&quot;]</value>
      <webElementGuid>c59ba227-7c38-40a3-bd26-dc7a7b716f73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>f2a00554-b570-41f8-9c9e-ccda0bfb5b9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='payment-form']/button</value>
      <webElementGuid>ae854502-c757-4a15-9ae8-e9ed2086ccad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Use a Different Method'])[1]/following::button[1]</value>
      <webElementGuid>e9a3b2e7-ead9-40dd-90ce-2790c841d0c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='****4242'])[1]/following::button[1]</value>
      <webElementGuid>9ee6d61c-2f20-48e0-ab30-f23d08b5b0db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please print a copy of your invoice and mail your check to:'])[1]/preceding::button[1]</value>
      <webElementGuid>e6f1d9c0-1d0d-489f-9996-7a6bd22a98cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company name:'])[1]/preceding::button[1]</value>
      <webElementGuid>cd1197b0-eae2-4999-8cf3-2307bdad3224</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pay $2,000.00']/parent::*</value>
      <webElementGuid>28fb5ecf-bff5-467a-bead-fb512d43c4eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button</value>
      <webElementGuid>788d8036-01c1-4354-8aed-f45a1e1f769c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Pay $2,000.00' or . = 'Pay $2,000.00')]</value>
      <webElementGuid>85969e29-c0f4-479b-b57d-cc6e13d6cf66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
