<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_US bank account</name>
   <tag></tag>
   <elementGuidId>003c6119-b40e-4a72-9c44-5fcc34c9b1d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#us_bank_account-tab</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='us_bank_account-tab']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>79d0c018-7beb-43e7-99ee-a784255b9e67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5f8235a9-14ee-4abd-aa2f-9bf0e5d4e5ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>us_bank_account</value>
      <webElementGuid>98206732-015b-474a-b964-81679e5738d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>us_bank_account-tab</value>
      <webElementGuid>c0f195ab-f415-4979-97c7-5e7d9f57da2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>50a52d0b-7cee-4f0e-a8f1-ed72bc765aad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>us_bank_account-panel</value>
      <webElementGuid>b0d97aff-cf59-40a6-91ea-622615325874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6f1e211b-af3e-4f0e-8ece-d88cc04e2c97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-setsize</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>7bab7f06-dded-42ec-a356-4dd8456ba954</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-Tab Tab</value>
      <webElementGuid>49bb9215-78c8-4aaa-b8c7-3d9da034917d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>69fd3ea7-0b80-4e20-8701-f382b4e5d5ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>37e7938d-8115-4422-a9dd-997f3a9b2262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>us_bank_account</value>
      <webElementGuid>73cf286d-9d7c-45e1-b2b9-bde484f76892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>US bank account</value>
      <webElementGuid>dd04f87f-39ec-4a76-925b-aa6bc60edd1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;us_bank_account-tab&quot;)</value>
      <webElementGuid>44867f95-6d70-4a31-8526-0f48d1ff272e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_SportWrench - The Home of Sporting Events/iframe_Use a Different Method___privateStri_862d4d</value>
      <webElementGuid>75aebb95-9425-45d5-bdfd-30da9e922e7d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='us_bank_account-tab']</value>
      <webElementGuid>bc7898b6-14a7-43ff-a295-4ef59575cdc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div/div/button[2]</value>
      <webElementGuid>f99e0d16-06d7-41ad-844f-1165cb76e831</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Card'])[1]/following::button[1]</value>
      <webElementGuid>187456f5-b1cb-432e-bee3-6fe639ac24ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Card number'])[1]/preceding::button[1]</value>
      <webElementGuid>24c716e7-ae96-46b1-b2bd-cd38f8da8973</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>7464e504-725a-4d19-9731-66bd941ca215</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'us_bank_account-tab' and (text() = 'US bank account' or . = 'US bank account')]</value>
      <webElementGuid>ab6b4d31-241c-4d0c-8dca-bca313dfd7a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
