<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Use a Different Method___privateStri_d224ff</name>
   <tag></tag>
   <elementGuidId>427864a5-afd3-4679-bb35-f6079424f3ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;__privateStripeFrame1685&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='__privateStripeFrame1685']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>9e00abd2-6146-4abb-acc5-f78e6279e916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>__privateStripeFrame1685</value>
      <webElementGuid>6e1518f7-c795-4e8d-9594-d152dcf455fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d65ef884-03b9-43b8-9ec7-7b804884deb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ce35df96-9e50-44d9-b321-6c43f92a1cc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>73f0c606-9f55-47a9-9d99-1160f97b44c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>ad16cb06-8e72-47d6-9933-40841145eb4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>payment *; publickey-credentials-get *</value>
      <webElementGuid>6d9e0414-31be-461f-bf3a-b4c44e0b6e6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://js.stripe.com/v3/elements-inner-payment-ef673aeb7c3e886c434586c418797aba.html#__shared_params__[version]=v3&amp;wait=false&amp;rtl=false&amp;publicOptions[paymentMethodOrder][0]=card&amp;publicOptions[paymentMethodOrder][1]=us_bank_account&amp;elementsInitSource=stripe.elements&amp;componentName=payment&amp;keyMode=test&amp;apiKey=pk_test_tFXze1a9YCyUsqvt06bECa8R&amp;referrer=https%3A%2F%2Fmy.dev.swstage.com%2F%23%2Fclub%2Fevent%2F25508%2Fteams%2Fpay&amp;controllerId=__privateStripeController1682</value>
      <webElementGuid>ed782c96-19b2-4038-89d3-b447ccaef1fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Secure payment input frame</value>
      <webElementGuid>57828b66-ff5a-45c7-950d-a0f4abe79412</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment-element&quot;)/div[@class=&quot;__PrivateStripeElement&quot;]/iframe[1]</value>
      <webElementGuid>039f0a4f-64c8-41cc-8e22-de9f9c93cd3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='__privateStripeFrame1685']</value>
      <webElementGuid>dc1f3ba0-4f54-42b8-b68e-0ee0a5a23d33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment-element']/div/iframe</value>
      <webElementGuid>e1a62966-79be-4b75-b3e9-3d3172140f42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>4737a66a-929c-455e-9ff4-db5aaa2417cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = '__privateStripeFrame1685' and @src = 'https://js.stripe.com/v3/elements-inner-payment-ef673aeb7c3e886c434586c418797aba.html#__shared_params__[version]=v3&amp;wait=false&amp;rtl=false&amp;publicOptions[paymentMethodOrder][0]=card&amp;publicOptions[paymentMethodOrder][1]=us_bank_account&amp;elementsInitSource=stripe.elements&amp;componentName=payment&amp;keyMode=test&amp;apiKey=pk_test_tFXze1a9YCyUsqvt06bECa8R&amp;referrer=https%3A%2F%2Fmy.dev.swstage.com%2F%23%2Fclub%2Fevent%2F25508%2Fteams%2Fpay&amp;controllerId=__privateStripeController1682' and @title = 'Secure payment input frame']</value>
      <webElementGuid>300578cd-ad5d-4894-a2a9-ab5cbec047a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
