<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Card number_number</name>
   <tag></tag>
   <elementGuidId>09fb062f-7a0c-470f-a4ca-97b5dbfcb8d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Field-numberInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Field-numberInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4b050033-0a36-4df5-9fbc-b8359b037ded</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>0acbf75a-545e-4417-ae74-a122a276db37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8d61e2c5-fb4a-43d5-91fa-9cc825578346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>a1dc0649-3413-41bd-819b-c4712466a634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>28229e49-c1e1-45e5-b7ac-c9675dbfe798</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Field-numberInput</value>
      <webElementGuid>d7506c43-543a-4127-abc5-900b865488b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>1234 1234 1234 1234</value>
      <webElementGuid>f086f156-6587-407f-9792-0fec709682a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>cc-number</value>
      <webElementGuid>bf205419-5cc2-4136-ad52-71b78823925d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f3641f36-1f1f-4f4d-9ff1-afcef58beccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>Field-numberError knownCardBrandDesc cardBrandIconsDesc</value>
      <webElementGuid>2fb28c36-cea2-4157-8a74-5cfca741ec27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a0c755b6-9353-49c0-b764-1e7b1f75d7bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-Input-input Input p-CardNumberInput-input p-Input--focused Input--empty p-Input-input--textRight</value>
      <webElementGuid>cd9ff836-33db-4f3b-9bec-f000c4df9c5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Field-numberInput&quot;)</value>
      <webElementGuid>26632d04-15c3-49b7-a981-0aace4c9fa74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_SportWrench - The Home of Sporting Events/iframe_Check___privateStripeFrame4195</value>
      <webElementGuid>ba704c1f-4759-4257-b965-1aa1bae9c0c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Field-numberInput']</value>
      <webElementGuid>746bfc7f-1db3-44a2-8bc3-a83404469b00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='card-panel']/div/div/form/div/div[2]/div/div/div/div/div/input</value>
      <webElementGuid>f41f1965-0202-492a-95f5-96b7b75f8730</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>8f63f629-aadd-46a4-97d2-bc5e2ec70074</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'number' and @id = 'Field-numberInput' and @placeholder = '1234 1234 1234 1234']</value>
      <webElementGuid>4e237fd1-b8af-44c8-bfd3-d0fd4a560de9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
