<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Security code_cvc (1)</name>
   <tag></tag>
   <elementGuidId>55dc0d93-0f2e-48f4-b790-e299099914df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Field-cvcInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Field-cvcInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>625dd49d-a0e8-40ce-91ad-20dcd9831da4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>9245cef4-84cc-4279-9fe3-77a03133174d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ea025d65-e7dd-41e7-b598-6dd16995fe25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>47580f77-9567-4e36-afea-cd5d548be2af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cvc</value>
      <webElementGuid>381c0d85-1f22-4657-b13f-6357f292d922</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Field-cvcInput</value>
      <webElementGuid>6a51ae0f-1876-4d7c-938d-ae42e00f890e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>CVC</value>
      <webElementGuid>cae0ca9b-ee97-4a34-9116-3c03eaaae0bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>cc-csc</value>
      <webElementGuid>01e98752-db2d-4e07-9b39-06d974d97929</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>46fff6d1-85ee-4f61-959f-30bb686ea5b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>Field-cvcError cvcDesc</value>
      <webElementGuid>7c92511d-54eb-4a73-a6eb-9a9145f884ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f3eda12c-18fb-49e0-a846-4261420e03de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-Input-input Input p-Input--focused Input--empty p-Input-input--textRight</value>
      <webElementGuid>55491656-f466-4ee3-aa8b-297d2bf75878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Field-cvcInput&quot;)</value>
      <webElementGuid>bf2063c9-7021-4f64-941f-3854c78e59a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_SportWrench - The Home of Sporting Events/iframe_Use a Different Method___privateStri_d224ff</value>
      <webElementGuid>0280ded8-5790-41a4-9f59-533ceab9116f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Field-cvcInput']</value>
      <webElementGuid>3c2653c8-5fc7-48c0-91dc-4495493b3922</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='card-panel']/div/div/form/div/div/div[3]/div/div/div/div/input</value>
      <webElementGuid>9f984d6c-7d60-43a0-8a86-d9edc4aacfc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/input</value>
      <webElementGuid>e8e78d7a-a760-4380-8992-1035eee68dc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'cvc' and @id = 'Field-cvcInput' and @placeholder = 'CVC']</value>
      <webElementGuid>e79b4e99-db1d-4128-a394-1b0391c71605</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
