<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_VISA4242</name>
   <tag></tag>
   <elementGuidId>cd732e13-8925-4ea6-9f69-e317051b0061</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.stripe-card</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='payment-form']/stripe-card-list/ul/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>5c6dbce1-f0cc-4e64-a589-0fa911aa1089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>stripe-card</value>
      <webElementGuid>bf62d57e-3827-410f-bfdb-927920171cb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'stripe-card-selected': $ctrl.cardSelected(c)}</value>
      <webElementGuid>051da6df-d645-4632-899d-61b7b183e8f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-repeat</name>
      <type>Main</type>
      <value>c in $ctrl.filteredCards</value>
      <webElementGuid>c5596525-bab7-4297-a586-0a0b4aa8ce60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>$ctrl.selectCard(c)</value>
      <webElementGuid>0a6c7445-d87f-4b2b-895a-80bf510acf93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>VISA****4242</value>
      <webElementGuid>5519bcd7-ba97-4a13-99da-0ceb8b9fe6a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment-form&quot;)/stripe-card-list[1]/ul[@class=&quot;stripe-card-list&quot;]/li[@class=&quot;stripe-card&quot;]</value>
      <webElementGuid>ab2a0e1e-3a62-40da-9141-29fd9e19913a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='payment-form']/stripe-card-list/ul/li</value>
      <webElementGuid>493843a3-d84a-4447-816e-bb9148a8f25a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check'])[1]/following::li[1]</value>
      <webElementGuid>1f9e3909-c9be-4e22-ad3d-cd057ae7069f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Online'])[1]/following::li[1]</value>
      <webElementGuid>29389e54-3c3c-4d2f-912c-0dae96f68f06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//stripe-card-list/ul/li</value>
      <webElementGuid>b5cb45c4-a482-4b4b-97af-11ac3d15aff9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'VISA****4242' or . = 'VISA****4242')]</value>
      <webElementGuid>eed44c7e-4ee0-49be-89b9-771c3a857159</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
