<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Refund_caret</name>
   <tag></tag>
   <elementGuidId>12bd54af-4172-4a2d-ba4c-e63c66b39525</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.caret</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='accordiongroup-1085-5060-panel']/div/div/div/div/div[2]/div/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Refund&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>613d98be-1696-461c-85a4-f4a78755c883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>caret</value>
      <webElementGuid>ecaa9e96-ab70-4744-8f8a-cf3a7ad14f28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accordiongroup-1085-5060-panel&quot;)/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-3&quot;]/div[@class=&quot;btn-group dropdown&quot;]/button[@class=&quot;btn btn-danger pull-right dropdown-toggle&quot;]/span[@class=&quot;caret&quot;]</value>
      <webElementGuid>fdbf378a-c9f6-4535-aa35-51dc0d092926</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordiongroup-1085-5060-panel']/div/div/div/div/div[2]/div/button/span</value>
      <webElementGuid>ee12c7c4-5c58-4841-88cd-59a4df47613c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span</value>
      <webElementGuid>087adb2c-d6b6-4627-9397-d8ae34080724</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
