<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Invoices_searchbox</name>
   <tag></tag>
   <elementGuidId>44083bc4-9b05-4034-9c7c-b0d9096c72e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;searchbox&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='searchbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Search ...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5717b9cf-c1ea-4aae-8c6e-ece8d0e1d530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>877df9c8-0f36-4d3f-818d-f367f2aa6093</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>searchbox</value>
      <webElementGuid>2502e296-88c4-4987-8759-d124bb702f44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control search_teams white-ro ng-empty</value>
      <webElementGuid>5455f9c8-da81-4dcd-87e7-0d96e405627a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search ...</value>
      <webElementGuid>1af21a24-a66f-4657-b942-74e257b58a22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>$ctrl.inputModel</value>
      <webElementGuid>d216c020-b679-49b3-98ac-59a3852c14c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-keyup</name>
      <type>Main</type>
      <value>$ctrl.onKeypress($event)</value>
      <webElementGuid>4547a8de-37f8-4a94-ac9d-ecaef59a498b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-readonly</name>
      <type>Main</type>
      <value>$ctrl.isReadonly()</value>
      <webElementGuid>ae5f349e-45be-4c99-9e81-763f9a264166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-js&quot;]/body[1]/div[@class=&quot;container-fluid block-height-min&quot;]/div[@class=&quot;container club-menu-container&quot;]/div[@class=&quot;tab-content clubownermenucontent&quot;]/div[@class=&quot;tab-pane active&quot;]/div[1]/form[@class=&quot;form-inline row-space ng-pristine ng-valid ng-valid-date&quot;]/div[@class=&quot;form-group&quot;]/sw-searchbox[1]/div[@class=&quot;form-group--custom sw-searchbox&quot;]/div[@class=&quot;search-box&quot;]/input[@class=&quot;form-control search_teams white-ro ng-empty&quot;]</value>
      <webElementGuid>a827a9e2-ef75-4170-963f-eb93d55a9a30</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='searchbox']</value>
      <webElementGuid>cc960b91-b80b-4bbd-b8b9-c20ca45026cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>3eb87eb0-4147-4e4e-9b20-3d0144960c72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'searchbox' and @placeholder = 'Search ...']</value>
      <webElementGuid>762fae27-5112-4761-b141-c7bde44b0dc1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
