<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_G18LAVAW10SC</name>
   <tag></tag>
   <elementGuidId>9ddef17a-1f0b-4f93-9143-cda773ca4ff3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='LAVA West 17 7'])[1]/following::div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;G18LAVAW10SC&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5b694f03-4959-4d1b-a909-79a46678b43b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-3</value>
      <webElementGuid>69766c2a-0b6f-4228-8b6d-6f1a43752c62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-bind</name>
      <type>Main</type>
      <value>item.code</value>
      <webElementGuid>9ba6f6d4-ab1e-432b-ae05-26b830eb24d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>G18LAVAW10SC</value>
      <webElementGuid>4a871329-aa7d-4562-ac57-a49d20cea84f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-js&quot;]/body[1]/div[@class=&quot;container-fluid block-height-min&quot;]/div[@class=&quot;container club-menu-container&quot;]/div[@class=&quot;tab-content clubownermenucontent&quot;]/div[@class=&quot;tab-pane active&quot;]/div[1]/form[@class=&quot;form-inline row-space top-menu ng-pristine ng-valid&quot;]/div[@class=&quot;btn-group dropdown open&quot;]/div[@class=&quot;dropdown-menu large-drop-down-menu dropdown-team-filter dropdown-scroll&quot;]/ul[@class=&quot;list-group&quot;]/li[@class=&quot;list-group-item clearfix pointer&quot;]/div[@class=&quot;col-3&quot;]</value>
      <webElementGuid>572a9181-4593-47b2-b3bd-8a324488eebc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LAVA West 17 7'])[1]/following::div[2]</value>
      <webElementGuid>3c98538e-997d-45d9-8e92-092bc9c06359</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='G17LAVAW7SC'])[1]/following::div[3]</value>
      <webElementGuid>15a13a6b-151e-4fd5-bacd-b4f371664ab8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LAVA West 18 10'])[1]/preceding::div[1]</value>
      <webElementGuid>134adc03-ccca-44e9-87b5-a731d9954a6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='G18LAVAW12SC'])[1]/preceding::div[3]</value>
      <webElementGuid>7471536c-78c2-4cdd-982f-3bb3d1842902</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='G18LAVAW10SC']/parent::*</value>
      <webElementGuid>4e36a452-1dd3-47e9-a0fc-86e55c0fc1b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[11]/div[2]</value>
      <webElementGuid>a30a8751-1447-4c3d-a42e-045b57f8b3de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'G18LAVAW10SC' or . = 'G18LAVAW10SC')]</value>
      <webElementGuid>8e721e86-d05e-4e9f-970f-793049643c63</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
