<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_USAV_ng-pristine ng-untouched ng-vali_2bf2f0_1_2_3_4_5_6</name>
   <tag></tag>
   <elementGuidId>993b4b03-a897-4e8e-a053-93e71a8eae74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='checkbox'])[14]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td > input.ng-pristine.ng-untouched.ng-valid.ng-empty</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;✉  Darynne Bickers IMPACT OK YES USAV&quot;i] >> internal:role=checkbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9131ba2f-18be-4e30-a609-fd084438e4cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>7fc05cd9-67e2-4717-96e8-0e55090f6add</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>opts.selection[st.master_staff_id]</value>
      <webElementGuid>f1b8c03a-5735-442b-8274-c9858878fe12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>staffCheckedChanged(st.master_staff_id);</value>
      <webElementGuid>e0689e2e-144f-4657-b181-246c00e39d82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid ng-empty</value>
      <webElementGuid>87b9a6f8-0593-4e4b-ac3e-b3fe0017f3e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-js&quot;]/body[1]/div[@class=&quot;container-fluid block-height-min&quot;]/div[@class=&quot;container club-menu-container&quot;]/div[@class=&quot;tab-content clubownermenucontent&quot;]/div[@class=&quot;tab-pane active&quot;]/div[1]/table[@class=&quot;table table-condensed&quot;]/tbody[@class=&quot;pointer&quot;]/tr[4]/td[1]/input[@class=&quot;ng-pristine ng-untouched ng-valid ng-empty&quot;]</value>
      <webElementGuid>6b9abf47-6565-48c1-89a5-534929b414eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='checkbox'])[14]</value>
      <webElementGuid>ab79af4f-21c4-4f14-bff9-1799ee8ef67e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td/input</value>
      <webElementGuid>a26787ba-65b9-4497-9fa4-8e55ec2a6c8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>91b6f500-9d4f-473d-9c20-e0836e56488f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
