<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_April 2025_1</name>
   <tag></tag>
   <elementGuidId>1fc378d4-7653-4204-8f51-a4294b5fcd62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#datepicker-616-751-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='datepicker-616-751-title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>690a7b1a-c405-4813-a181-528847cad270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>datepicker-616-751-title</value>
      <webElementGuid>b142a5d3-21ba-4d9a-8a7f-19e2c7e49a7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>heading</value>
      <webElementGuid>8272f3c6-7a9a-4a72-bf18-7fd4e5cc1790</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>assertive</value>
      <webElementGuid>1df5af1a-e8a6-4b9b-a493-158646716684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-atomic</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4a71bb9e-675c-4d75-b092-2c5454b6abd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>76bb5178-f6b7-4c9c-94bc-ea844ca782e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default btn-sm uib-title</value>
      <webElementGuid>4ccfa6fb-a9bd-44d3-8e6e-a7fe916e61d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>toggleMode()</value>
      <webElementGuid>33893d1f-8f9b-4a0a-8141-1b674b3c0c89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>datepickerMode === maxMode</value>
      <webElementGuid>9005b840-c5a0-49c7-bd9c-e7480a6c7f32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>8da1b92b-3372-4de6-8156-14fc125ada21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>April 2025</value>
      <webElementGuid>98ab1596-4bbc-48f9-827b-88c829b35e9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datepicker-616-751-title&quot;)</value>
      <webElementGuid>46fae5d7-c7cb-4329-b357-905b5268b6bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='datepicker-616-751-title']</value>
      <webElementGuid>d0c703ae-284b-4989-9acf-9a608ae399f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date Start'])[1]/following::button[2]</value>
      <webElementGuid>c3ca54ec-4aa4-43a7-9544-5537736c240a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sport Variation'])[1]/following::button[2]</value>
      <webElementGuid>ff2a082d-7fb3-4969-84e6-55c0322c5c36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sun'])[1]/preceding::button[2]</value>
      <webElementGuid>7009104c-bb55-4ab3-a78b-92af1f188497</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[2]/button</value>
      <webElementGuid>c59e8ef4-01a8-43d6-8c73-f2491ab6668e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'datepicker-616-751-title' and @type = 'button' and (text() = 'April 2025' or . = 'April 2025')]</value>
      <webElementGuid>1c975a27-7c2c-423f-9e2c-c0615de81e6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
