<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_25</name>
   <tag></tag>
   <elementGuidId>6ea2022b-11fe-475a-b983-8ac2e986853e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#datepicker-861-4184-30 > button.btn.btn-default.btn-sm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[34]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ff3fc415-72d6-4510-8227-c0620124153e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>39afa382-bf92-47f5-ac51-160182cb3247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default btn-sm</value>
      <webElementGuid>74553d75-99d2-4e1c-8eeb-d6266c9252a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>uib-is-class</name>
      <type>Main</type>
      <value>
            'btn-info' for selectedDt,
            'active' for activeDt
            on dt</value>
      <webElementGuid>c108c889-48d8-4119-814f-20c4e286b2dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>select(dt.date)</value>
      <webElementGuid>557606d3-dfe7-4143-be76-3b92f8269168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>::dt.disabled</value>
      <webElementGuid>7c21a1b3-e23f-4db4-8f2c-7517b8965350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>a7fffba9-9cd0-4f8c-acf1-c096ed527702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>963541f7-7dcc-4fd1-916e-bd349eb7e63e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datepicker-861-4184-30&quot;)/button[@class=&quot;btn btn-default btn-sm&quot;]</value>
      <webElementGuid>9bba400b-33b6-47f3-bedb-06a27c66c721</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[34]</value>
      <webElementGuid>2c15cb9a-f320-4a47-9d93-1f7e8026cb78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='datepicker-861-4184-30']/button</value>
      <webElementGuid>ecf4910e-4e65-44c8-9de9-7266754f52f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sat'])[1]/following::button[31]</value>
      <webElementGuid>9ecf8bfa-1bf4-44b9-96b9-ae428d1cadec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fri'])[1]/following::button[31]</value>
      <webElementGuid>21d47140-c59e-4f8f-bbcf-cbc80f395bf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Today'])[1]/preceding::button[12]</value>
      <webElementGuid>34bb7d5e-9372-41d8-9ab4-20cb038f11eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear'])[1]/preceding::button[13]</value>
      <webElementGuid>b8f849ac-dfcd-4ddd-b6e7-dec5db2f44a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[3]/button</value>
      <webElementGuid>19630647-6f95-49d6-80c3-f12b47295c21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '25' or . = '25')]</value>
      <webElementGuid>6256eae3-340b-4cc2-b482-9a35cefd85c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
