<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_Organization NameAddressCityStateProvi_0c35e9</name>
   <tag></tag>
   <elementGuidId>0a09fc18-1bda-4611-bf6f-c3d7df6b8aee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>form[name=&quot;hostForm&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@name='hostForm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>72b20e6b-9e21-454a-bacc-d00e17d130d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>hostForm</value>
      <webElementGuid>95bf6994-9b31-4f56-a069-324242817c6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-horizontal ng-invalid ng-invalid-required ng-valid-usa-zip ng-valid-mask ng-valid-phone ng-valid-url ng-valid-email ng-valid-social ng-dirty ng-valid-parse</value>
      <webElementGuid>7ac4bf80-be7f-4110-a9a5-a4edef5f733d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tournament</name>
      <type>Main</type>
      <value>tournament</value>
      <webElementGuid>bf89f844-df8c-4763-9f3f-a1d2a39913ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Organization NameAddressCityState/ProvinceSelect...AlabamaAlaskaAlbertaArizonaArkansasBritish ColombiaCaliforniaColoradoConnecticutDelawareDistrict of ColumbiaFloridaGeorgiaHawaiiIdahoIllinoisIndianaIowaKansasKentuckyLouisianaMaineManitobaMarylandMassachusettsMichiganMinnesotaMississippiMissouriMontanaNebraskaNevadaNew BrunswickNew HampshireNew JerseyNew MexicoNew YorkNewfoundland and LabradorNorth CarolinaNorth DakotaNova ScotiaOhioOklahomaOntarioOregonPennsylvaniaPrince Edward IslandQuébecRhode IslandSaskatchewanSouth CarolinaSouth DakotaTennesseeTexasUtahVermontVirginiaWashingtonWest VirginiaWisconsinWyomingZIPPhoneWebsite URLRules Website URLThis URL will be sent by email to entered teams. Leave it empty to use Website URL.EmailNotify Frequency of NotificationsNeverHourlyDailyImmediatelyHow often do you want to receive notifications of actions such as new entries</value>
      <webElementGuid>4860b09c-27e3-4d50-a126-36fd3f902937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-js&quot;]/body[1]/div[@class=&quot;container-fluid block-height-min&quot;]/event-settings[1]/div[@class=&quot;container no-animate&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-10 col-sm-offset-1&quot;]/div[1]/div[@class=&quot;tab-content&quot;]/div[@class=&quot;tab-pane active&quot;]/general-settings[1]/div[@class=&quot;row-space&quot;]/uib-accordion[1]/div[@class=&quot;panel-group&quot;]/div[@class=&quot;panel panel-info panel-open&quot;]/div[@class=&quot;in collapse&quot;]/div[@class=&quot;panel-body&quot;]/form[@class=&quot;form-horizontal ng-invalid ng-invalid-required ng-valid-usa-zip ng-valid-mask ng-valid-phone ng-valid-url ng-valid-email ng-valid-social ng-dirty ng-valid-parse&quot;]</value>
      <webElementGuid>b743201a-f47d-43f0-9ef7-d36237cefa4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//form[@name='hostForm']</value>
      <webElementGuid>534a7869-e828-4947-a148-bcffa8ccd4d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Host Organization Information'])[1]/following::form[1]</value>
      <webElementGuid>a9fb3062-10ad-444a-98e3-37b2f852e55a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show Event on SW Home page and SW Tickets'])[1]/following::form[1]</value>
      <webElementGuid>e2c57cb2-037a-45de-9b6f-db6d54383a52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/form</value>
      <webElementGuid>867f5a6f-3460-4e1b-a119-bbaacef8a1e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//form[@name = 'hostForm' and (text() = 'Organization NameAddressCityState/ProvinceSelect...AlabamaAlaskaAlbertaArizonaArkansasBritish ColombiaCaliforniaColoradoConnecticutDelawareDistrict of ColumbiaFloridaGeorgiaHawaiiIdahoIllinoisIndianaIowaKansasKentuckyLouisianaMaineManitobaMarylandMassachusettsMichiganMinnesotaMississippiMissouriMontanaNebraskaNevadaNew BrunswickNew HampshireNew JerseyNew MexicoNew YorkNewfoundland and LabradorNorth CarolinaNorth DakotaNova ScotiaOhioOklahomaOntarioOregonPennsylvaniaPrince Edward IslandQuébecRhode IslandSaskatchewanSouth CarolinaSouth DakotaTennesseeTexasUtahVermontVirginiaWashingtonWest VirginiaWisconsinWyomingZIPPhoneWebsite URLRules Website URLThis URL will be sent by email to entered teams. Leave it empty to use Website URL.EmailNotify Frequency of NotificationsNeverHourlyDailyImmediatelyHow often do you want to receive notifications of actions such as new entries' or . = 'Organization NameAddressCityState/ProvinceSelect...AlabamaAlaskaAlbertaArizonaArkansasBritish ColombiaCaliforniaColoradoConnecticutDelawareDistrict of ColumbiaFloridaGeorgiaHawaiiIdahoIllinoisIndianaIowaKansasKentuckyLouisianaMaineManitobaMarylandMassachusettsMichiganMinnesotaMississippiMissouriMontanaNebraskaNevadaNew BrunswickNew HampshireNew JerseyNew MexicoNew YorkNewfoundland and LabradorNorth CarolinaNorth DakotaNova ScotiaOhioOklahomaOntarioOregonPennsylvaniaPrince Edward IslandQuébecRhode IslandSaskatchewanSouth CarolinaSouth DakotaTennesseeTexasUtahVermontVirginiaWashingtonWest VirginiaWisconsinWyomingZIPPhoneWebsite URLRules Website URLThis URL will be sent by email to entered teams. Leave it empty to use Website URL.EmailNotify Frequency of NotificationsNeverHourlyDailyImmediatelyHow often do you want to receive notifications of actions such as new entries')]</value>
      <webElementGuid>5de06609-18fa-4181-8b74-3ef3b5585868</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
