<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Open Date_reg_open</name>
   <tag></tag>
   <elementGuidId>cda65139-e18d-4125-a522-0954fc7817fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;reg_open&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='reg_open']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>db7a3029-8fd6-4417-a9f5-07f020f004ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d0351d9e-2358-4166-9151-bc1198b7ce61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>white-ro form-control pointer ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required ng-valid-datetime</value>
      <webElementGuid>73646433-a116-4e48-931a-ba1dae00212b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datetime-picker</name>
      <type>Main</type>
      <value>MM/dd/yyyy HH:mm</value>
      <webElementGuid>2f0b453c-e1b3-4bba-841a-eb6e01a4bcd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min-date</name>
      <type>Main</type>
      <value>minDate</value>
      <webElementGuid>2f27e9f5-826b-461f-8d72-ce6a7f4100ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max-date</name>
      <type>Main</type>
      <value>maxDate</value>
      <webElementGuid>c2a38185-63cc-49da-b91b-d378aaf4273a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>is-open</name>
      <type>Main</type>
      <value>settings.isOpen</value>
      <webElementGuid>fda07e7a-7205-49b2-aab0-8e42faeed45f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>toggleOpen()</value>
      <webElementGuid>8b08783a-3559-4ba6-bc7f-5c0451afeb56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>0a792320-cb47-4b62-99c6-fba619b18987</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model-options</name>
      <type>Main</type>
      <value>{ debounce: 400 }</value>
      <webElementGuid>6cd5d1ad-39d4-4834-b1a5-093cd32e19d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reg_open</value>
      <webElementGuid>ab4aa3f5-f720-4223-8eb4-5fa8ab6ddbe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datepicker-options</name>
      <type>Main</type>
      <value>{showWeeks: false}</value>
      <webElementGuid>70ca2afb-ad76-49cc-ae38-4f1337fe1482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>fieldRequired</value>
      <webElementGuid>e69c6a19-3ae8-4f5d-9f56-af828e125c37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>change()</value>
      <webElementGuid>4d39bc3d-b019-45e9-a7e8-498772369bc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enable-time</name>
      <type>Main</type>
      <value>disableTimepicker</value>
      <webElementGuid>0e99d693-aecf-4fed-be94-65a2725bb725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>037b7284-c401-4b07-8254-75b9e568e098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>e622a55e-f0c1-45e5-9440-75054ee47dc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-js&quot;]/body[1]/div[@class=&quot;container-fluid block-height-min&quot;]/event-settings[1]/div[@class=&quot;container no-animate&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-10 col-sm-offset-1&quot;]/div[1]/div[@class=&quot;tab-content&quot;]/div[@class=&quot;tab-pane active&quot;]/general-settings[1]/div[@class=&quot;row-space&quot;]/uib-accordion[1]/div[@class=&quot;panel-group&quot;]/div[@class=&quot;panel panel-info panel-open&quot;]/div[@class=&quot;in collapse&quot;]/div[@class=&quot;panel-body&quot;]/form[@class=&quot;form-horizontal ng-invalid ng-invalid-required ng-invalid-min ng-valid-reg_close ng-valid-deadline ng-valid-datetime ng-dirty ng-valid-parse&quot;]/div[2]/div[@class=&quot;register-dates-teams col-sm-10 col-sm-offset-1&quot;]/div[@class=&quot;form-group validation-required&quot;]/div[@class=&quot;col-sm-5&quot;]/div[@class=&quot;input-group date-time-control form-control[disabled]&quot;]/input[@class=&quot;white-ro form-control pointer ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required ng-valid-datetime&quot;]</value>
      <webElementGuid>b1ff0911-3aeb-45c3-b9d2-eb9255df53f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='reg_open']</value>
      <webElementGuid>4d9699d5-2592-4baf-8f65-c8a377125380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/input</value>
      <webElementGuid>b6c16379-cb7c-4e8d-aa5d-c19c926a96c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'reg_open']</value>
      <webElementGuid>0cb75b32-c519-4c34-b278-91d4b1bfd0d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
