<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Statement Descriptor_stripe_statement</name>
   <tag></tag>
   <elementGuidId>4470848d-8e22-4bd1-8966-edb46e8c933d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;stripe_statement&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='stripe_statement']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1c269218-5a4b-4b7a-bf6e-649e3dc7e242</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>baef2071-a5f3-4a9f-ac9d-8dc4047ced83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-empty ng-valid-forbidden-letters ng-invalid ng-invalid-required ng-valid-maxlength</value>
      <webElementGuid>5165b07c-e253-4335-b3ff-c988a317c885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>$ctrl.ngModel</value>
      <webElementGuid>9bf78df4-357d-4f39-8771-5ca495be3d02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>stripe_statement</value>
      <webElementGuid>2752a0e7-3d6a-4009-9646-85ab1461061b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-maxlength</name>
      <type>Main</type>
      <value>22</value>
      <webElementGuid>35c3303b-080d-49db-ad57-7482c85b1400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>$ctrl.isRequired</value>
      <webElementGuid>1df3955c-9f22-4380-85ea-4bee9e095117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>ff208218-8047-4aa8-b0d4-af064226e3b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-js&quot;]/body[1]/div[@class=&quot;container-fluid block-height-min&quot;]/event-settings[1]/div[@class=&quot;container no-animate&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-10 col-sm-offset-1&quot;]/div[1]/div[@class=&quot;tab-content&quot;]/div[@class=&quot;tab-pane active&quot;]/general-settings[1]/div[@class=&quot;row-space&quot;]/uib-accordion[1]/div[@class=&quot;panel-group&quot;]/div[@class=&quot;panel panel-info panel-open&quot;]/div[@class=&quot;in collapse&quot;]/div[@class=&quot;panel-body&quot;]/form[@class=&quot;form-horizontal ng-valid-usa-zip ng-dirty ng-valid-parse ng-valid-min ng-invalid ng-invalid-required ng-valid-forbidden-letters ng-valid-maxlength&quot;]/fieldset[1]/statement-descriptor-input[@class=&quot;ng-pristine ng-untouched ng-valid ng-empty&quot;]/div[@class=&quot;form-group validation-required&quot;]/div[@class=&quot;col-sm-7&quot;]/input[@class=&quot;form-control ng-pristine ng-untouched ng-empty ng-valid-forbidden-letters ng-invalid ng-invalid-required ng-valid-maxlength&quot;]</value>
      <webElementGuid>ad9e3987-68f4-483d-a91e-fb00ede58525</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='stripe_statement']</value>
      <webElementGuid>92f6af69-305f-4861-8571-779d36fa5137</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//statement-descriptor-input/div/div/input</value>
      <webElementGuid>f0ccfdde-b96a-47f9-8403-816348018bb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'stripe_statement']</value>
      <webElementGuid>4c5e5539-2b86-4588-8f92-5dd845911034</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
