<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Credit Surcharge_surcharge</name>
   <tag></tag>
   <elementGuidId>1f813560-bff8-4a04-80c8-2bbba03e4bc9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;surcharge&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='surcharge']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0cc82ff8-d4bb-4346-b851-f5502a94737c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>5ea4f5e1-d829-40be-b23e-7ddd7b6b9005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-empty ng-valid-min ng-invalid ng-invalid-required</value>
      <webElementGuid>d75f4a4a-097f-42eb-bd7e-17552ffd9203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>tournament.credit_surcharge</value>
      <webElementGuid>280f5219-a505-4f8c-83f5-e4d5871ca0cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>surcharge</value>
      <webElementGuid>b391025d-b71b-4733-85ae-7b026a47a8b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>33e30996-bfcb-445c-a6b5-1a3515ba1b60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-js&quot;]/body[1]/div[@class=&quot;container-fluid block-height-min&quot;]/event-settings[1]/div[@class=&quot;container no-animate&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-10 col-sm-offset-1&quot;]/div[1]/div[@class=&quot;tab-content&quot;]/div[@class=&quot;tab-pane active&quot;]/general-settings[1]/div[@class=&quot;row-space&quot;]/uib-accordion[1]/div[@class=&quot;panel-group&quot;]/div[@class=&quot;panel panel-info panel-open&quot;]/div[@class=&quot;in collapse&quot;]/div[@class=&quot;panel-body&quot;]/form[@class=&quot;form-horizontal ng-valid-usa-zip ng-dirty ng-valid-parse ng-valid-min ng-invalid ng-invalid-required ng-valid-forbidden-letters ng-valid-maxlength&quot;]/fieldset[1]/div[@class=&quot;form-group validation-required&quot;]/div[@class=&quot;col-sm-8&quot;]/div[@class=&quot;input-group col-sm-4&quot;]/input[@class=&quot;form-control ng-pristine ng-untouched ng-empty ng-valid-min ng-invalid ng-invalid-required&quot;]</value>
      <webElementGuid>28b60585-50fd-47b7-8e4e-6adce76b56ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='surcharge']</value>
      <webElementGuid>fb55b657-5fa7-45bb-bb95-e061d99ca9d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div/div/input</value>
      <webElementGuid>8662b7b1-4c97-4784-a11d-46e2cd266912</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'surcharge']</value>
      <webElementGuid>0dffe451-72fc-4692-b4d8-b25cf1f0a07b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
