<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Roster Deadline_deadline</name>
   <tag></tag>
   <elementGuidId>9acd016b-6e0a-42fe-a925-46884368f8bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;deadline&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='deadline']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>21f049b3-bbb9-480b-89f0-1410794d7fcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>62af5c8a-d05b-474a-938d-dc2442de6a7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>white-ro form-control pointer ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required ng-valid-datetime</value>
      <webElementGuid>56f3bcd3-9e2f-4f8f-b35e-5734bc45617f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datetime-picker</name>
      <type>Main</type>
      <value>MM/dd/yyyy HH:mm</value>
      <webElementGuid>f3a33c46-c049-4b1a-a2f4-d6d3bf7308b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min-date</name>
      <type>Main</type>
      <value>minDate</value>
      <webElementGuid>c019c61f-5f0d-4aa8-abca-dbe55b59b885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max-date</name>
      <type>Main</type>
      <value>maxDate</value>
      <webElementGuid>3fa73d31-fde7-4831-bffc-a1ebc3392793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>is-open</name>
      <type>Main</type>
      <value>settings.isOpen</value>
      <webElementGuid>6ef9169e-3933-4bb3-bc91-f1025bef5c26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>toggleOpen()</value>
      <webElementGuid>5d88e1e2-869e-46f2-9b9b-aec7cafcd935</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>ccef8a4d-e969-4028-aee6-37bff04ae058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model-options</name>
      <type>Main</type>
      <value>{ debounce: 400 }</value>
      <webElementGuid>4a709356-3a1d-48f7-b1e8-54a8103c9e72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>deadline</value>
      <webElementGuid>1fe5af79-5dcd-433b-8810-a73bb6dbd478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datepicker-options</name>
      <type>Main</type>
      <value>{showWeeks: false}</value>
      <webElementGuid>f11b77ce-c926-4fba-b86e-20a278adade7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>fieldRequired</value>
      <webElementGuid>1711f543-6c3f-4284-a36a-6bd294fa31b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>change()</value>
      <webElementGuid>4d5fa1c3-85e2-494b-b60b-31bb073ddbb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enable-time</name>
      <type>Main</type>
      <value>disableTimepicker</value>
      <webElementGuid>b70208ed-817a-4c04-8716-2490026a8fe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>bed8fde8-01b2-4754-ab95-704ee4ba75d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>d96021f2-4d84-43b6-bd4b-021e867e1262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-js&quot;]/body[1]/div[@class=&quot;container-fluid block-height-min&quot;]/event-settings[1]/div[@class=&quot;container no-animate&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-10 col-sm-offset-1&quot;]/div[1]/div[@class=&quot;tab-content&quot;]/div[@class=&quot;tab-pane active&quot;]/general-settings[1]/div[@class=&quot;row-space&quot;]/uib-accordion[1]/div[@class=&quot;panel-group&quot;]/div[@class=&quot;panel panel-info panel-open&quot;]/div[@class=&quot;in collapse&quot;]/div[@class=&quot;panel-body&quot;]/form[@class=&quot;form-horizontal ng-invalid ng-invalid-required ng-valid-reg_close ng-valid-deadline ng-valid-datetime ng-dirty ng-valid-parse ng-valid-number ng-valid-min&quot;]/div[2]/div[@class=&quot;form-group validation-required&quot;]/div[@class=&quot;col-sm-4&quot;]/div[@class=&quot;input-group date-time-control ng-pristine ng-untouched ng-valid ng-empty ng-valid-deadline&quot;]/input[@class=&quot;white-ro form-control pointer ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required ng-valid-datetime&quot;]</value>
      <webElementGuid>f2f7d78d-86b6-457a-ae5e-bf09f94022e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='deadline']</value>
      <webElementGuid>572df842-cb64-4cf0-be37-f0d418deae5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[19]/div/div/input</value>
      <webElementGuid>aa672ba7-dab9-4970-8ae0-fb91e81af46f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'deadline']</value>
      <webElementGuid>41d213a6-eff0-43c6-9835-565428b90889</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/div/div/input</value>
      <webElementGuid>369426d3-5744-472b-9eb2-f284939511a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
