<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__form-control text-center ng-pristine_dd8360</name>
   <tag></tag>
   <elementGuidId>276bd0ec-12e1-4f81-a9df-8ac4439aa610</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.form-control.text-center.ng-pristine.ng-untouched.ng-valid.ng-valid-maxlength.ng-not-empty</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a97a66da-00a5-4cd8-ae62-9bf224dd12cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7f3f3238-39dc-4673-ab6d-a6746bd09556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>MM</value>
      <webElementGuid>73ffcb87-19e8-4f67-91c4-9d7799bc6cb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>minutes</value>
      <webElementGuid>24e02cb9-d16f-472a-be70-3891e4c1c168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>updateMinutes()</value>
      <webElementGuid>eceedc0a-f16f-45f6-8b4c-3ee91516ae48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-center ng-pristine ng-untouched ng-valid ng-valid-maxlength ng-not-empty</value>
      <webElementGuid>9c7c0524-180f-4581-9c42-70d3c4520c48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-readonly</name>
      <type>Main</type>
      <value>::readonlyInput</value>
      <webElementGuid>09244df3-fbd5-46ca-87af-750eca1c955b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>bc57b598-0f82-43be-93ec-fb8a4b5554f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c88871f4-56c8-44c8-b164-60b6a323519a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>noIncrementMinutes()</value>
      <webElementGuid>0c319a8d-a026-4340-8e9c-0e4de5632f00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-blur</name>
      <type>Main</type>
      <value>blur()</value>
      <webElementGuid>8b9bf87f-e31e-478d-ad45-d4e6c64e7aec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-js&quot;]/body[1]/div[@class=&quot;container-fluid block-height-min&quot;]/event-settings[1]/div[@class=&quot;container no-animate&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-10 col-sm-offset-1&quot;]/div[1]/div[@class=&quot;tab-content&quot;]/div[@class=&quot;tab-pane active&quot;]/general-settings[1]/div[@class=&quot;row-space&quot;]/uib-accordion[1]/div[@class=&quot;panel-group&quot;]/div[@class=&quot;panel panel-info panel-open&quot;]/div[@class=&quot;in collapse&quot;]/div[@class=&quot;panel-body&quot;]/form[@class=&quot;form-horizontal ng-valid-maxlength ng-valid-date_end ng-valid-datetime ng-dirty ng-valid-parse ng-invalid ng-invalid-event-dates ng-valid-time ng-valid-required&quot;]/div[@class=&quot;form-group validation-required has-error&quot;]/div[@class=&quot;col-sm-4&quot;]/div[@class=&quot;input-group date-time-control ng-pristine ng-untouched ng-valid ng-valid-date_end ng-not-empty&quot;]/ul[@class=&quot;dropdown-menu dropdown-menu-left datetime-picker-dropdown ng-untouched ng-dirty ng-valid-parse ng-valid ng-valid-time ng-not-empty&quot;]/li[@class=&quot;time-picker-menu&quot;]/div[1]/table[@class=&quot;uib-timepicker&quot;]/tbody[1]/tr[2]/td[@class=&quot;form-group uib-time minutes&quot;]/input[@class=&quot;form-control text-center ng-pristine ng-untouched ng-valid ng-valid-maxlength ng-not-empty&quot;]</value>
      <webElementGuid>af873a93-520e-430a-8226-9aff76127d07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[6]</value>
      <webElementGuid>240e68c6-49e8-45c6-830f-224847143dd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/input</value>
      <webElementGuid>c1c54c9a-a15a-42b0-9dfe-60f1cafae82e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'MM']</value>
      <webElementGuid>ac406e6f-f74e-4072-81c3-68e2965db880</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
