<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Choose a Stripe Account .Lev (lev.ku_173092</name>
   <tag></tag>
   <elementGuidId>ecf2afca-3648-42f3-830b-12e82b838f17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;stripe_account&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='stripe_account']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>fdb8c470-aed7-47a0-a1dd-5de0305c86ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>stripe_account</value>
      <webElementGuid>5725d522-20eb-4924-a261-336f080870cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required</value>
      <webElementGuid>c7d992db-ea37-48a0-8ef6-6dae57f5b637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>$ctrl.accountId</value>
      <webElementGuid>bb6b3b13-c3dc-4aeb-bb67-0fd3a116bc30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>$ctrl._onChange()</value>
      <webElementGuid>3c659bd8-168a-41ce-a47b-1836d3b2b7db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-options</name>
      <type>Main</type>
      <value>acc.account_id as $ctrl.accLabel(acc) disable when acc.is_disabled for acc in $ctrl.utils.stripeAccounts</value>
      <webElementGuid>d7244a5c-3ad7-44f7-830a-e3e5792bbec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>!$ctrl.isLoading()</value>
      <webElementGuid>ed1ce0c4-dba6-457f-b9fb-e030263f568c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Choose a Stripe Account ...Lev (lev.kuzmenko11@gmail.com)TEST: fapl.ru (null)TEST: Account not available for current user (N/A)</value>
      <webElementGuid>a34cdb28-c598-4402-9bb6-0866147e1a4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-js&quot;]/body[1]/div[@class=&quot;container-fluid block-height-min&quot;]/event-settings[1]/div[@class=&quot;container no-animate&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-10 col-sm-offset-1&quot;]/div[1]/div[@class=&quot;tab-content&quot;]/div[@class=&quot;tab-pane active&quot;]/general-settings[1]/div[@class=&quot;row-space&quot;]/uib-accordion[1]/div[@class=&quot;panel-group&quot;]/div[@class=&quot;panel panel-info panel-open&quot;]/div[@class=&quot;in collapse&quot;]/div[@class=&quot;panel-body&quot;]/form[@class=&quot;form-horizontal ng-valid-usa-zip ng-dirty ng-valid-parse ng-valid-min ng-invalid ng-invalid-required ng-valid-forbidden-letters ng-valid-maxlength ng-valid-number&quot;]/fieldset[1]/stripe-account-select[1]/div[@class=&quot;form-group validation-required&quot;]/div[@class=&quot;col-sm-7&quot;]/select[@class=&quot;form-control ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required&quot;]</value>
      <webElementGuid>c6169669-2b81-4c0e-b090-23951f2c0c44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='stripe_account']</value>
      <webElementGuid>28d06481-8c0f-45ef-852a-b885deb0413b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stripe Account'])[1]/following::select[1]</value>
      <webElementGuid>6479ba5f-0735-4890-98a0-72b6fa6e8a6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$'])[2]/following::select[1]</value>
      <webElementGuid>9b02d059-c138-40c4-99bc-ff703fa05b02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Main Location'])[1]/preceding::select[1]</value>
      <webElementGuid>fb4769ef-6456-449b-85e7-4e3a054ff732</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Location name'])[1]/preceding::select[1]</value>
      <webElementGuid>fede9bbf-7b8a-4fea-a68f-4690b84960da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//stripe-account-select/div/div/select</value>
      <webElementGuid>c1c5afc5-4bca-45d2-981b-caec2128013d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'stripe_account' and (text() = 'Choose a Stripe Account ...Lev (lev.kuzmenko11@gmail.com)TEST: fapl.ru (null)TEST: Account not available for current user (N/A)' or . = 'Choose a Stripe Account ...Lev (lev.kuzmenko11@gmail.com)TEST: fapl.ru (null)TEST: Account not available for current user (N/A)')]</value>
      <webElementGuid>724b2f12-4f0a-4680-9a01-609749225368</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
