<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_30_1</name>
   <tag></tag>
   <elementGuidId>9df0a0bb-f822-4b3b-8f46-4e80ef876d87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#datepicker-985-6704-30 > button.btn.btn-default.btn-sm > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='datepicker-985-6704-30']/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5d038bea-8ac9-4135-9a66-6058e1b388bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>::{'text-muted': dt.secondary, 'text-info': dt.current}</value>
      <webElementGuid>27b7fe20-6975-4804-b9a9-d92d9d7298b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>e66d3ab1-e3e4-44b7-8d5e-9c430297e53c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datepicker-985-6704-30&quot;)/button[@class=&quot;btn btn-default btn-sm&quot;]/span[1]</value>
      <webElementGuid>e04c3c21-a126-421d-be73-ba4dc17e9b5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='datepicker-985-6704-30']/button/span</value>
      <webElementGuid>c2a8348a-b100-4524-9b4f-d637aaa1337c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sat'])[1]/following::span[31]</value>
      <webElementGuid>673b5f24-c6a8-41bb-b7b6-b0338d8815f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fri'])[1]/following::span[31]</value>
      <webElementGuid>21718304-c9ed-4480-9bb8-60011ffcc9ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Today'])[1]/preceding::span[12]</value>
      <webElementGuid>53931aa9-422f-4584-a6c9-ce3e0e1d5adf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear'])[1]/preceding::span[12]</value>
      <webElementGuid>64db2547-ea26-4a5d-bf29-88e814a87e60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[3]/button/span</value>
      <webElementGuid>4c1eb5ef-68e6-461a-a1b3-7f0be2883c92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '30' or . = '30')]</value>
      <webElementGuid>3bcc7437-b1c1-4c5d-8aa9-e9f1636125d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
