<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_29</name>
   <tag></tag>
   <elementGuidId>237bfe30-f611-49df-8e09-a99998a2581b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#datepicker-282-8965-30 > button.btn.btn-default.btn-sm > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='datepicker-282-8965-30']/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b2c11bfb-1652-4561-8af4-a67ea4169323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>::{'text-muted': dt.secondary, 'text-info': dt.current}</value>
      <webElementGuid>5a84ffb1-0c37-4ee2-be7a-5c6e8f55029a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>29</value>
      <webElementGuid>1a293184-7cf5-4c62-af1a-8c3bfd8c6d40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datepicker-282-8965-30&quot;)/button[@class=&quot;btn btn-default btn-sm&quot;]/span[1]</value>
      <webElementGuid>d8e2f4b2-5c38-48fa-8db8-8c88e0266284</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='datepicker-282-8965-30']/button/span</value>
      <webElementGuid>ba5871e9-e826-45fa-8d52-1bcf1a530031</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sat'])[1]/following::span[31]</value>
      <webElementGuid>e7b2701e-6b92-4e13-abd1-4a26264f6f4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fri'])[1]/following::span[31]</value>
      <webElementGuid>e8dd02a6-50bd-46b0-97b4-fcbbc61906e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Today'])[1]/preceding::span[12]</value>
      <webElementGuid>5d6f177c-b437-41a5-9d44-477849bfc15c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear'])[1]/preceding::span[12]</value>
      <webElementGuid>b588d4f8-1f74-4c7a-945f-6ff8ad7c2f12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='29']/parent::*</value>
      <webElementGuid>b693ffbe-a4c8-4a91-8c61-8d17d4dad854</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[3]/button/span</value>
      <webElementGuid>d5d942f8-8538-445d-bbb6-56321e9d0a90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '29' or . = '29')]</value>
      <webElementGuid>d09231e8-6876-4ddc-b5ac-0ace2c458973</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
