<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_edit_form-control input-sm ng-pristin_1ea9ba_1 (1)</name>
   <tag></tag>
   <elementGuidId>545490b3-c3da-44c5-9fe3-ca3bc22c5f90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(2) > td.text-right > div.editable-cell.block-lg > input.form-control.input-sm.ng-pristine.ng-untouched.ng-valid.ng-empty.w-sm.pull-right</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[15]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d83c6c18-2bb5-40e6-ac09-639eb3e8774d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>elType !== 'select' &amp;&amp; elType !== 'checkbox'</value>
      <webElementGuid>ed8c89ef-2ad5-4916-afc4-81c439b7533e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4e2bfeda-384a-4546-b46c-c18e7d471041</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>utils.val</value>
      <webElementGuid>a6132de8-7fda-4f9b-8242-46b5c15352dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-sm ng-pristine ng-untouched ng-valid ng-empty w-sm pull-right</value>
      <webElementGuid>0bed8758-f26c-42de-8769-bbf1df70c646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'w-sm pull-right': priceType(), 'w-lg': !priceType()}</value>
      <webElementGuid>4cb83012-2de0-4842-89cb-61b8b3feb7c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>00.00</value>
      <webElementGuid>94bf35ff-8861-4975-97d2-0975702c9b69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-show</name>
      <type>Main</type>
      <value>isEditing</value>
      <webElementGuid>bbf94892-2876-4ff5-9fae-1ab8a2f8c18c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>onChange()</value>
      <webElementGuid>2d7e9f82-e628-4f48-a388-ef0a360a87f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-js&quot;]/body[1]/div[@class=&quot;container-fluid block-height-min&quot;]/div[@class=&quot;row rowm0&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;tab-content eo-dashboard&quot;]/div[@class=&quot;tab-pane active&quot;]/div[1]/tickets-table[1]/div[@class=&quot;row row-mb--20&quot;]/div[@class=&quot;col-md-12&quot;]/table[@class=&quot;table tickets-table&quot;]/tbody[1]/tr[2]/td[@class=&quot;text-right&quot;]/div[@class=&quot;editable-cell block-lg&quot;]/input[@class=&quot;form-control input-sm ng-pristine ng-untouched ng-valid ng-empty w-sm pull-right&quot;]</value>
      <webElementGuid>7fd517d0-6aea-438f-8885-c23323866f92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[15]</value>
      <webElementGuid>493c0449-c7c7-479c-8452-84989bbf4994</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[10]/div/input</value>
      <webElementGuid>da9c6b1d-2cec-48e3-a529-07ffa25fd12d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = '00.00']</value>
      <webElementGuid>e9d4197b-0e46-40f1-adc6-9e5df7e39fb1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
