<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Other Events_searchbox</name>
   <tag></tag>
   <elementGuidId>9a847ea2-9641-4d0e-bdfa-11c88bec119e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;searchbox&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='searchbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2ab7fbea-6401-4047-972f-d37b688c34c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1e3c57ce-bda1-4550-97e8-c256ae80a8fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>searchbox</value>
      <webElementGuid>df78fbbe-a24b-4b42-8d10-733e2e030b20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control search_teams white-ro ng-empty</value>
      <webElementGuid>1d99dd7f-5f28-4da8-9a67-021f8de0dc02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search...</value>
      <webElementGuid>86efff46-6ed5-42fd-bd7d-6e8ec5547941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>$ctrl.inputModel</value>
      <webElementGuid>1fefc9d9-d480-4730-a0f9-d787a6806308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-keyup</name>
      <type>Main</type>
      <value>$ctrl.onKeypress($event)</value>
      <webElementGuid>6c1d224b-c534-4676-a580-85bcd43190ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-readonly</name>
      <type>Main</type>
      <value>$ctrl.isReadonly()</value>
      <webElementGuid>648b821f-20ef-45af-a0e3-2223a223ee8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-js&quot;]/body[1]/div[@class=&quot;container-fluid block-height-min&quot;]/div[1]/div[@class=&quot;tab-content&quot;]/div[@class=&quot;tab-pane active&quot;]/events-list[1]/div[@class=&quot;form-inline row-space&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;search-box search-input&quot;]/sw-searchbox[1]/div[@class=&quot;form-group--custom sw-searchbox&quot;]/div[@class=&quot;search-box&quot;]/input[@class=&quot;form-control search_teams white-ro ng-empty&quot;]</value>
      <webElementGuid>c1de0b2f-93d8-4291-a55f-f940a330e2b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='searchbox']</value>
      <webElementGuid>8746ee27-b91f-4a76-85c7-605de24477a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>cb3cbf4b-1737-47bd-a71e-359833a9ad61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'searchbox' and @placeholder = 'Search...']</value>
      <webElementGuid>8f205c44-bfdb-484e-be7a-7ad38fd323a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
