<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Other Events_searchbox (1)</name>
   <tag></tag>
   <elementGuidId>3ec922cd-4f5c-4a2d-85c3-8cd76eab45f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;searchbox&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='searchbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>364d32fd-caed-4be6-9824-2fd920dfd5e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f3c6bb9e-c7c1-4e77-ac63-30f56cade4b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>searchbox</value>
      <webElementGuid>156dc948-6572-40c3-9aef-e658d9333b0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control search_teams white-ro ng-empty</value>
      <webElementGuid>3c2e36d5-6060-4420-b0cb-c15747d5f8b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search...</value>
      <webElementGuid>a0c82305-5215-468c-9d11-bd35d2824272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>$ctrl.inputModel</value>
      <webElementGuid>ee88c7c1-691f-42ec-a229-7e28182c4b19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-keyup</name>
      <type>Main</type>
      <value>$ctrl.onKeypress($event)</value>
      <webElementGuid>c4d09ce6-9ba3-4202-accc-b25e68f37a41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-readonly</name>
      <type>Main</type>
      <value>$ctrl.isReadonly()</value>
      <webElementGuid>144b97d9-9f03-4e2a-aaeb-1c68ab22a4ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-js&quot;]/body[1]/div[@class=&quot;container-fluid block-height-min&quot;]/div[1]/div[@class=&quot;tab-content&quot;]/div[@class=&quot;tab-pane active&quot;]/events-list[1]/div[@class=&quot;form-inline row-space&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;search-box search-input&quot;]/sw-searchbox[1]/div[@class=&quot;form-group--custom sw-searchbox&quot;]/div[@class=&quot;search-box&quot;]/input[@class=&quot;form-control search_teams white-ro ng-empty&quot;]</value>
      <webElementGuid>ed1a3a3b-9048-46bd-a439-17c8eb6be401</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='searchbox']</value>
      <webElementGuid>78396334-b21d-4fb6-87fc-de34cf4121ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>be762273-b793-4d3f-9e00-52cd4689b48f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'searchbox' and @placeholder = 'Search...']</value>
      <webElementGuid>95784fe9-bb37-4194-adae-6da72833bb0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
