<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_To_white-ro form-control pointer ng-p_bf3a2b (1)</name>
   <tag></tag>
   <elementGuidId>9ee89435-4d3d-4a44-981d-ad3809d3a00d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.white-ro.form-control.pointer.ng-pristine.ng-untouched.ng-valid.ng-empty.ng-valid-datetime</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>54071616-d318-4739-916d-3abb15d736aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>eab97d29-c003-4b6a-99ac-5111b11abebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>white-ro form-control pointer ng-pristine ng-untouched ng-valid ng-empty ng-valid-datetime</value>
      <webElementGuid>c6bf0489-1d7d-40d6-961b-75b972d6eb44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datetime-picker</name>
      <type>Main</type>
      <value>MM/dd yyyy, hh:mm a</value>
      <webElementGuid>db3e9322-984e-4b95-9cd2-b34f9ddf0fb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>is-open</name>
      <type>Main</type>
      <value>utils.pickerEndOpened</value>
      <webElementGuid>77aebd93-a361-42df-8f78-cf6fad8f4f43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>uib-timepicker-options</name>
      <type>Main</type>
      <value>utils.pickerDateEnd</value>
      <webElementGuid>c3861ccb-aac2-4b68-9ef7-47e557890f70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>utils.pickerEndOpened = !utils.pickerEndOpened</value>
      <webElementGuid>9804e700-a2b0-48e9-b2c9-7a2cfc9f583d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>utils.end</value>
      <webElementGuid>78dedcff-399d-4564-a93e-05b35bde483e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>765e03b0-bc54-4580-9b53-2f159933b53d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-js&quot;]/body[1]/div[@class=&quot;container-fluid block-height-min&quot;]/div[@class=&quot;row rowm0&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;tab-content eo-dashboard&quot;]/div[@class=&quot;tab-pane active&quot;]/div[1]/div[@class=&quot;row row-space rowm0&quot;]/div[@class=&quot;tickets-settings-form col-xs-12 col-sm-4&quot;]/div[@class=&quot;input-group date-time-control col-md-8 col-sm-10&quot;]/input[@class=&quot;white-ro form-control pointer ng-pristine ng-untouched ng-valid ng-empty ng-valid-datetime&quot;]</value>
      <webElementGuid>ebb30e70-90be-4293-91a9-74536fa1dba3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[2]</value>
      <webElementGuid>4f18d004-d6b9-47db-8753-845448da6125</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>f9f9da7d-a0a4-42ff-857d-96a2c8ec2c41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>d82b17dd-5eb6-4f0c-9d23-088e5630b62b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
