<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_MM  YY_expiry</name>
   <tag></tag>
   <elementGuidId>fa34b145-e94c-48d5-be2b-c2402dbd73b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Field-expiryInput']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Field-expiryInput</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;MM / YY&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1cd0d2e8-bcde-4125-89c8-0a4c80bdff3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>a52efb12-8694-44f4-a1aa-1ff9723a713d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c476b4ad-a87d-49c9-9756-7bf95d088514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>3adec4af-6a8a-4c00-a59d-6e41d6da9bae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>expiry</value>
      <webElementGuid>ba059976-2007-4464-8acc-043db8e3dab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Field-expiryInput</value>
      <webElementGuid>c2a2fdad-045f-4e36-bf28-62d8a9d5e3c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>MM / YY</value>
      <webElementGuid>b09950ff-d133-4992-b4f3-3b8b8944cab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>cc-exp</value>
      <webElementGuid>958a9e04-19cb-42f3-a504-9e7ec9e9f744</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2c6a5544-272a-45d3-98fc-4f7460164e0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>Field-expiryError</value>
      <webElementGuid>f3690a6e-f3cc-4317-930d-5a69664e8939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>651d4502-f3be-4582-90aa-0a1f9cc46284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-Input-input Input p-Input--focused Input--empty p-Input-input--textRight</value>
      <webElementGuid>93aec5ee-242b-42b8-8378-66f4f1339caf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Field-expiryInput&quot;)</value>
      <webElementGuid>dc1a99a7-bd6a-444a-9772-e2f9dcd35163</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Team Payment/Page_SportWrench - The Home of Sporting Events/iframe_Use a Different Method___privateStri_8b553a</value>
      <webElementGuid>3f8929bf-66ea-4bb4-910d-30054d71d4d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Field-expiryInput']</value>
      <webElementGuid>c4d68a4b-9798-4901-a548-913a23847f75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='card-panel']/div/div/form/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>b0231830-f210-400a-b130-997aeaf9b382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/input</value>
      <webElementGuid>d7fd2d1b-f8b7-4347-a782-d1dbc3fccb02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'expiry' and @id = 'Field-expiryInput' and @placeholder = 'MM / YY']</value>
      <webElementGuid>df5c0935-7114-4c0b-85f7-ab7a187f8d7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
