<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_VISA4242</name>
   <tag></tag>
   <elementGuidId>3fcfde29-ed22-471c-a8f4-c4451c267d06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.stripe-card</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='payment-form']/stripe-card-list/ul/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>8aeffbaf-fbee-4a43-8fe6-bc9b2102bcc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>stripe-card</value>
      <webElementGuid>0cdc7644-f94d-4e9a-95db-c5151392a315</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'stripe-card-selected': $ctrl.cardSelected(c)}</value>
      <webElementGuid>8039ed25-c3c5-4958-9539-4518bc6fa378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-repeat</name>
      <type>Main</type>
      <value>c in $ctrl.filteredCards</value>
      <webElementGuid>cd92387b-9b1c-46e0-8480-3408045c5fd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>$ctrl.selectCard(c)</value>
      <webElementGuid>53a501e2-06e2-469b-aa92-392c80dc452f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>VISA****4242</value>
      <webElementGuid>cf358017-1929-49f8-8b86-0bdc264c7305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment-form&quot;)/stripe-card-list[1]/ul[@class=&quot;stripe-card-list&quot;]/li[@class=&quot;stripe-card&quot;]</value>
      <webElementGuid>53e42199-16a3-41c4-8091-204d6312ce4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='payment-form']/stripe-card-list/ul/li</value>
      <webElementGuid>dbd84699-3a3a-4acf-86b0-3f4eb5beabe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check'])[1]/following::li[1]</value>
      <webElementGuid>e69a2f9a-5715-4835-91a6-d078971d7276</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Online'])[1]/following::li[1]</value>
      <webElementGuid>c19c0c2e-e33d-406e-900d-a6a0a183fbf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//stripe-card-list/ul/li</value>
      <webElementGuid>af741592-0cec-4eaa-9889-5d488b66f5de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'VISA****4242' or . = 'VISA****4242')]</value>
      <webElementGuid>cdada15d-ac8b-4f76-b1e2-f3a8634c89b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
