<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_1,000.00_1</name>
   <tag></tag>
   <elementGuidId>447b66c8-5959-4972-a77d-b76bbff40173</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.ml7 > b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='accordiongroup-1037-254-tab']/h4/a/span/payment-info-accord-heading/span/span/b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>8777ed41-ac9b-45b8-b4b1-370a780cf6a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$1,000.00</value>
      <webElementGuid>c3101193-144f-4825-9aa7-6472eb3d396b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accordiongroup-1037-254-tab&quot;)/h4[@class=&quot;panel-title&quot;]/a[@class=&quot;accordion-toggle&quot;]/span[1]/payment-info-accord-heading[1]/span[@class=&quot;text-success&quot;]/span[@class=&quot;ml7&quot;]/b[1]</value>
      <webElementGuid>5c4466dc-c2d4-43fc-a36f-9efeae06944b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordiongroup-1037-254-tab']/h4/a/span/payment-info-accord-heading/span/span/b</value>
      <webElementGuid>f0a07b0d-797b-4714-962f-0a9887f46d02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CARD (paid)'])[1]/following::b[1]</value>
      <webElementGuid>8ae1400b-78ee-491c-93fa-3e54e2b19842</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/following::b[1]</value>
      <webElementGuid>5fc3f9e6-ea00-4012-8197-2dbebc079b79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created:'])[1]/preceding::b[1]</value>
      <webElementGuid>0f8daa84-1fb8-475d-aaf2-40644b8bfb1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payer:'])[1]/preceding::b[1]</value>
      <webElementGuid>a6c4922d-7371-4ae6-bfbe-ee01f9e2f2e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$1,000.00']/parent::*</value>
      <webElementGuid>7ea2bd62-7e3d-498d-b1aa-898c96fa912b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/b</value>
      <webElementGuid>21644755-922c-4e94-82e1-0d3d199608d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = '$1,000.00' or . = '$1,000.00')]</value>
      <webElementGuid>ea6d3e85-51aa-4f97-a162-cfad29c75ebe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
