<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_1,000.00_1_2</name>
   <tag></tag>
   <elementGuidId>7081cc46-3ade-41eb-9a66-91302572aff9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.ml7 > b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='accordiongroup-1022-4709-tab']/h4/a/span/payment-info-accord-heading/span/span/b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>8ced1ce1-dcad-4430-9dd1-8e2fd5a49510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$1,000.00</value>
      <webElementGuid>f05cb970-ae13-4c47-b82a-de706d869562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accordiongroup-1022-4709-tab&quot;)/h4[@class=&quot;panel-title&quot;]/a[@class=&quot;accordion-toggle&quot;]/span[1]/payment-info-accord-heading[1]/span[@class=&quot;text-success&quot;]/span[@class=&quot;ml7&quot;]/b[1]</value>
      <webElementGuid>e360b431-e68c-4a8a-91e7-7e4bffb18fd7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordiongroup-1022-4709-tab']/h4/a/span/payment-info-accord-heading/span/span/b</value>
      <webElementGuid>109e33e6-217e-4e61-bdad-911ffd9bdbb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CARD (paid)'])[1]/following::b[1]</value>
      <webElementGuid>9fb351e3-1354-41ef-b882-4ebd5d2c084a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/following::b[1]</value>
      <webElementGuid>4c7f08e2-d63c-4d12-a3d5-4c1fe1c3bc70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created:'])[1]/preceding::b[1]</value>
      <webElementGuid>52be251c-aa20-4f2c-b5c6-b18c09c9ebf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payer:'])[1]/preceding::b[1]</value>
      <webElementGuid>afd33e25-ee1e-40e8-8fad-af4982e54958</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$1,000.00']/parent::*</value>
      <webElementGuid>a7960dc2-c42e-4088-8462-b8690069698b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/b</value>
      <webElementGuid>0fe1bc3f-60ef-47c0-9fb4-aa85ea229e37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = '$1,000.00' or . = '$1,000.00')]</value>
      <webElementGuid>b45c7902-7fca-426f-9ed6-d9edb2bfe27f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
