<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_1,000.00_1_2_3</name>
   <tag></tag>
   <elementGuidId>4fb4010c-7864-4c93-8880-c4bb292ee824</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.ml7 > b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='accordiongroup-1037-68-tab']/h4/a/span/payment-info-accord-heading/span/span/b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>3fecb727-b132-4d73-9584-c49ff24936ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$1,000.00</value>
      <webElementGuid>66bd0bfc-f893-4367-970a-61d5f305b382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accordiongroup-1037-68-tab&quot;)/h4[@class=&quot;panel-title&quot;]/a[@class=&quot;accordion-toggle&quot;]/span[1]/payment-info-accord-heading[1]/span[@class=&quot;text-success&quot;]/span[@class=&quot;ml7&quot;]/b[1]</value>
      <webElementGuid>2dec4afe-6d01-40bc-90f2-244d51606b24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordiongroup-1037-68-tab']/h4/a/span/payment-info-accord-heading/span/span/b</value>
      <webElementGuid>bb88bbf5-54fd-4f5c-8a37-2a46a0ebab7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CARD (paid)'])[1]/following::b[1]</value>
      <webElementGuid>d79ecec6-1a3a-42d1-a944-3d20c16e196a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/following::b[1]</value>
      <webElementGuid>a80772b4-3799-47cb-bf61-2ccdbc8311c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created:'])[1]/preceding::b[1]</value>
      <webElementGuid>e21b17e2-c2ad-40e2-ae1f-ba9fc36936ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payer:'])[1]/preceding::b[1]</value>
      <webElementGuid>4bc7c0b9-14d2-4960-839f-44d8d1eebc45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$1,000.00']/parent::*</value>
      <webElementGuid>3b2c74c5-ba54-41a6-9c12-a46417cc29cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/b</value>
      <webElementGuid>69b62b75-418b-416e-b75c-a19a90bb16f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = '$1,000.00' or . = '$1,000.00')]</value>
      <webElementGuid>15fde183-3234-4524-9611-3bad2e5d823e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
