<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Spectator_clubDirector</name>
   <tag></tag>
   <elementGuidId>37baa704-db75-4068-8b0e-14506b58d71c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#clubDirector</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='clubDirector']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Club Director&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4de8fd2e-e69a-410c-8e3f-4a7ae9e6aafc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>clubDirector</value>
      <webElementGuid>086a3da6-a906-4b68-855c-adff97ae3e45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>8fe3b36a-add2-4bea-9477-a82b174eaaa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-label</value>
      <webElementGuid>5d079f0e-7e05-4929-98c2-4ea18e5bb9cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;clubDirector&quot;)</value>
      <webElementGuid>5d412586-bcb5-4168-9b46-a72f23ba3117</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='clubDirector']</value>
      <webElementGuid>a20f4bff-d2c6-4197-b8ea-1eb3cad4ca23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[2]/div/div/div/input</value>
      <webElementGuid>00b1bc56-3fcd-43a3-9f6a-3d6c9579f729</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'clubDirector' and @type = 'checkbox']</value>
      <webElementGuid>0b2f84db-417c-41c2-b8e8-46bb7293fc50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
