<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Registration_first</name>
   <tag></tag>
   <elementGuidId>688376e5-54a0-48f8-942d-21cc2a63b70c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;first&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='first']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;First Name*&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>74e1e9fe-4df5-4fea-acb0-ae7ac68f4bad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>First Name*</value>
      <webElementGuid>04765e88-ff9c-44dc-ac8e-f2cdb42e41da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>first</value>
      <webElementGuid>36e1b0a6-79cd-4a6b-a855-4f52e3b238ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control signup-input-first-name</value>
      <webElementGuid>9429bc08-44db-4819-bd78-6da3dcb0a9d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fad09593-e295-438e-a33f-879e08965cf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0d31ea86-429c-4977-aabe-be89a79ea488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[1]/div[@class=&quot;content&quot;]/form[@class=&quot;wrapper-signup&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12  col-sm-12 col-md-6 col-lg-4 col-xl-4&quot;]/div[@class=&quot;signup-form&quot;]/div[@class=&quot;mb-3&quot;]/input[@class=&quot;form-control signup-input-first-name&quot;]</value>
      <webElementGuid>54d5d728-dd60-411a-92ae-0dabca81fca8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='first']</value>
      <webElementGuid>733cca81-258c-4ea9-a031-467a35fbbeef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>7fea51d7-258c-46a7-8aeb-707c43d94c1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'First Name*' and @name = 'first']</value>
      <webElementGuid>61503984-988f-4a90-ac25-820d62815aaf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
