<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Security code_cvc</name>
   <tag></tag>
   <elementGuidId>3dfb4379-daf1-4df3-84fc-059219083565</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Field-cvcInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Field-cvcInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c2165920-0739-4684-97b2-cf9ab8a48e81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>09c0e6e2-35eb-4575-bd96-2192dec6f0de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>850ee7b6-5ca7-4312-bb69-aad7f8d5e247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>2dfaa3c3-2a38-4476-8ed7-00e49a9a9816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cvc</value>
      <webElementGuid>dfed5bcd-e920-4577-baf2-f2450c8c56d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Field-cvcInput</value>
      <webElementGuid>5697f997-dc95-4146-89c8-2240fc905176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>CVC</value>
      <webElementGuid>bb56d0ba-c58f-4800-bd10-79c2aa42047a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>cc-csc</value>
      <webElementGuid>55bfd499-fd7d-4629-bc0e-51f240c3b833</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8335fbdf-d506-4dd8-9e3e-140d07c4dc63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>Field-cvcError cvcDesc</value>
      <webElementGuid>a3f24af1-8257-4395-8829-8aaba987a084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2195c743-4da0-42c1-9125-00ed90b6dbdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-Input-input Input p-Input--focused Input--empty p-Input-input--textRight</value>
      <webElementGuid>cab90eb2-e1a4-450e-ad39-c9120343ff87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Field-cvcInput&quot;)</value>
      <webElementGuid>bdb5f0cf-64a4-4fe5-8485-89f4b36d6a77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Ticket Purchase/Page_Ticket Purchase/iframe_Payment___privateStripeFrame1244</value>
      <webElementGuid>d54d1b65-8fdf-457c-8c72-b00fa6381206</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Field-cvcInput']</value>
      <webElementGuid>44951d29-20fa-47e7-9d7b-cd57e90d70f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='card-panel']/div/div/form/div/div/div[3]/div/div/div/div/input</value>
      <webElementGuid>23a30f05-70e1-4ddc-8687-83f2e28efbe3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/input</value>
      <webElementGuid>59fbd0ae-dfe0-4415-b052-d52e8b7b1c21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'cvc' and @id = 'Field-cvcInput' and @placeholder = 'CVC']</value>
      <webElementGuid>87f433ed-bdf5-4e95-850a-394712282883</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
