<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Location name_name</name>
   <tag></tag>
   <elementGuidId>ac2dc78b-71e1-4740-ad96-63db4645b4f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>form[name=&quot;utils.locationForm&quot;] > div.form-group.validation-required > div.col-sm-7 > input[name=&quot;name&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='name'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6d2c676a-929a-46f8-8c7c-a2198a748fd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>3d7fca82-52a1-45f5-914f-5336d62b3401</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8fa276db-9215-42f7-b4b7-86ead3e8806c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required</value>
      <webElementGuid>7a6c9d84-ce9c-44f5-94af-470e96b0d054</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Location Name ...</value>
      <webElementGuid>8f7c0a83-0895-4e88-baae-c0a1e32caf6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>location.name</value>
      <webElementGuid>2aab9446-9e2d-4626-ba28-5ad80bed45fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-js&quot;]/body[1]/div[@class=&quot;container-fluid block-height-min&quot;]/event-settings[1]/div[@class=&quot;container no-animate&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-10 col-sm-offset-1&quot;]/div[1]/div[@class=&quot;tab-content&quot;]/div[@class=&quot;tab-pane active&quot;]/general-settings[1]/div[@class=&quot;row-space&quot;]/uib-accordion[1]/div[@class=&quot;panel-group&quot;]/div[@class=&quot;panel panel-info panel-open&quot;]/div[@class=&quot;in collapse&quot;]/div[@class=&quot;panel-body&quot;]/ng-include[1]/form[@class=&quot;form-horizontal ng-pristine ng-invalid ng-invalid-required ng-valid-maxlength ng-valid-usa-zip ng-valid-min ng-valid-max&quot;]/div[@class=&quot;form-group validation-required&quot;]/div[@class=&quot;col-sm-7&quot;]/input[@class=&quot;form-control ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required&quot;]</value>
      <webElementGuid>5fe421cd-feea-42d5-9f4e-93daf166bb93</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='name'])[2]</value>
      <webElementGuid>3f582e2b-2340-4259-b612-c33806bda91c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-include/form/div/div/input</value>
      <webElementGuid>eb7cb54c-fd9a-431f-ad78-3b8627b9b37b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'name' and @type = 'text' and @placeholder = 'Location Name ...']</value>
      <webElementGuid>8afec0c1-9bcf-48f6-ab2f-dba87ea4be63</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
