<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Other Events_searchbox</name>
   <tag></tag>
   <elementGuidId>63f15da5-2c14-4f05-ac16-d4d7edf827a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='searchbox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;searchbox&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Search...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>399fe257-3fa6-4e2d-b60e-985a3630fe93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e91f0c62-f861-4781-8844-ab45c8096d11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>searchbox</value>
      <webElementGuid>1f200a4f-bd36-43c3-9768-7ba549932874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control search_teams white-ro ng-empty</value>
      <webElementGuid>0c50d7e7-a698-486c-84ca-f132211d5c04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search...</value>
      <webElementGuid>7324a42d-6e71-46e5-8a86-827cbc3e17ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>$ctrl.inputModel</value>
      <webElementGuid>6c18fb57-0fee-435b-b4df-5ad606581c02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-keyup</name>
      <type>Main</type>
      <value>$ctrl.onKeypress($event)</value>
      <webElementGuid>d9d7561f-5706-40b0-b6fc-548439b7206e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-readonly</name>
      <type>Main</type>
      <value>$ctrl.isReadonly()</value>
      <webElementGuid>c23e2304-39e9-452d-9510-ef056cd5abdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-js&quot;]/body[1]/div[@class=&quot;container-fluid block-height-min&quot;]/div[1]/div[@class=&quot;tab-content&quot;]/div[@class=&quot;tab-pane active&quot;]/events-list[1]/div[@class=&quot;form-inline row-space&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;search-box search-input&quot;]/sw-searchbox[1]/div[@class=&quot;form-group--custom sw-searchbox&quot;]/div[@class=&quot;search-box&quot;]/input[@class=&quot;form-control search_teams white-ro ng-empty&quot;]</value>
      <webElementGuid>e544c1e3-9ccc-417e-96ec-4230a6c7af60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='searchbox']</value>
      <webElementGuid>1d9bcfd4-bb6c-4eca-ae7e-197eda4255e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>7975b73a-c038-4f10-8600-c7d82c325bc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'searchbox' and @placeholder = 'Search...']</value>
      <webElementGuid>64fd3ab1-305d-4ca0-a6d4-b7af19d1e325</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
