<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__form-control form-control-4digits ng_fc52e6</name>
   <tag></tag>
   <elementGuidId>cf511bd2-9db1-4fed-9b70-fd4d7511b176</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='number'])[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.form-control.form-control-4digits.ng-untouched.ng-valid.ng-valid-min.ng-empty.ng-dirty.ng-valid-number</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;$1,000.00 $ $ 13 Club Trinity 9 10&quot;i] >> internal:role=spinbutton >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>613311d7-11a2-4d68-827e-2c6282444d40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>1e317e0a-e5a2-44f7-8c04-a99632f530a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>62684469-773a-4bdf-b198-6650f193770b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-4digits ng-untouched ng-valid ng-valid-min ng-empty ng-dirty ng-valid-number</value>
      <webElementGuid>42bbfe46-9929-4a2d-b100-50eac34ec29c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>t.discount</value>
      <webElementGuid>a19d1880-4b02-4340-8224-2a5d7ff5ea35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>t.is_refunded</value>
      <webElementGuid>e58b697f-7700-4fa1-8c0c-aa1e15d0001d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>onRefundedAmountChange(t)</value>
      <webElementGuid>5a80b009-a80f-4192-9f6d-576b7c241b43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accordiongroup-4236-514-panel&quot;)/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12&quot;]/partial-refund[1]/table[@class=&quot;table table-condensed eo-partial-refund&quot;]/tbody[1]/tr[3]/td[3]/div[@class=&quot;input-group&quot;]/input[@class=&quot;form-control form-control-4digits ng-untouched ng-valid ng-valid-min ng-empty ng-dirty ng-valid-number&quot;]</value>
      <webElementGuid>ab5a876f-2a73-404d-9d26-63a63fde2f6a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='number'])[6]</value>
      <webElementGuid>1e238b87-d349-4084-b12a-1d3a40da498f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordiongroup-4236-514-panel']/div/div/div/partial-refund/table/tbody/tr[3]/td[3]/div/input</value>
      <webElementGuid>c81a9f9a-15f7-4809-aa2d-8c75e6eeb177</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/div/input</value>
      <webElementGuid>ee1a7714-fb9c-4ba8-a8fb-9447f024ca3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number']</value>
      <webElementGuid>42515a4f-0276-4bd5-9c26-60c9970f4931</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
