<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe____privateStripeFrame22225</name>
   <tag></tag>
   <elementGuidId>73429955-d9ea-4750-9e7b-4bbe0315e2fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;__privateStripeFrame22225&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='__privateStripeFrame22225']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>981aa82c-e967-4360-96f5-20ae3ce05835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>__privateStripeFrame22225</value>
      <webElementGuid>f7295f35-0ef5-4251-a7f6-2e31f879b3e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>59874b71-fb68-4017-928a-5baa300c3905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6f916d55-c34f-408c-9382-169fadec4d73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>3fd2e686-2972-48c0-98a1-0df62c674347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>99ffbaf6-b45b-4ac5-acf8-32eb0b4ec6bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>payment *</value>
      <webElementGuid>024ee06d-480a-4b8b-8be8-6dfbddf1ac08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://js.stripe.com/v3/elements-inner-card-09a08d28bfbbdd899927efc1c73ac594.html#__shared_params__[version]=v3&amp;wait=false&amp;mids[guid]=8c4617f8-9004-435b-9b8d-2edc0c60bc06d180a5&amp;mids[muid]=4b564ec6-a980-407d-912f-4bdb5b2df08dd9bc76&amp;mids[sid]=eda7b236-a048-45e7-b5c2-8be98b328ce73e5b66&amp;hidePostalCode=true&amp;style[base][color]=%23000000&amp;style[base][lineHeight]=16px&amp;style[base][fontFamily]=%22Helvetica+Neue%22%2C+Helvetica%2C+sans-serif&amp;style[base][fontSize]=14px&amp;style[base][::placeholder][color]=%236c6c6c&amp;style[invalid][color]=%23FD423B&amp;style[invalid][iconColor]=%23FD423B&amp;rtl=false&amp;componentName=card&amp;keyMode=test&amp;apiKey=pk_test_tFXze1a9YCyUsqvt06bECa8R&amp;referrer=https%3A%2F%2Ftickets-dev.swstage.com%2Fbuy%2F%3Fevent%3D516434627&amp;controllerId=__privateStripeController22219</value>
      <webElementGuid>d3a70f2e-a150-409a-af40-2bbf6d567ccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Secure card payment input frame</value>
      <webElementGuid>e4baa8b0-9bc1-4b50-aeb3-81734a34e6e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;card-element&quot;)/div[@class=&quot;__PrivateStripeElement&quot;]/iframe[1]</value>
      <webElementGuid>a4cb09f9-5ff8-4e83-8ba2-c2c3278f6aaa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='__privateStripeFrame22225']</value>
      <webElementGuid>6bc4db35-4903-45d1-a87f-82c7e199c682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='card-element']/div/iframe</value>
      <webElementGuid>abb8ca8e-236c-4dbb-bab2-33ab68aed825</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>47d33b4e-b482-49bc-8735-3afc306eac8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = '__privateStripeFrame22225' and @src = 'https://js.stripe.com/v3/elements-inner-card-09a08d28bfbbdd899927efc1c73ac594.html#__shared_params__[version]=v3&amp;wait=false&amp;mids[guid]=8c4617f8-9004-435b-9b8d-2edc0c60bc06d180a5&amp;mids[muid]=4b564ec6-a980-407d-912f-4bdb5b2df08dd9bc76&amp;mids[sid]=eda7b236-a048-45e7-b5c2-8be98b328ce73e5b66&amp;hidePostalCode=true&amp;style[base][color]=%23000000&amp;style[base][lineHeight]=16px&amp;style[base][fontFamily]=%22Helvetica+Neue%22%2C+Helvetica%2C+sans-serif&amp;style[base][fontSize]=14px&amp;style[base][::placeholder][color]=%236c6c6c&amp;style[invalid][color]=%23FD423B&amp;style[invalid][iconColor]=%23FD423B&amp;rtl=false&amp;componentName=card&amp;keyMode=test&amp;apiKey=pk_test_tFXze1a9YCyUsqvt06bECa8R&amp;referrer=https%3A%2F%2Ftickets-dev.swstage.com%2Fbuy%2F%3Fevent%3D516434627&amp;controllerId=__privateStripeController22219' and @title = 'Secure card payment input frame']</value>
      <webElementGuid>a0275313-8960-431a-9c46-abe8bac269ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
