<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__purchaserZipCode</name>
   <tag></tag>
   <elementGuidId>21b784f5-571e-403c-8a4e-0a262d6fba30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#purchaserZipCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='purchaserZipCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1ab2e556-0087-451f-ab3d-a115db0f8834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>purchaserZipCode</value>
      <webElementGuid>69f3fec8-c6da-4859-a257-b451ffb7d88c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>purchaserZipCode</value>
      <webElementGuid>f85bd33f-80e5-4a9e-9891-acbaba279b44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Billing Zip Code</value>
      <webElementGuid>25028eb4-4bdc-45c7-a09d-4c9827fada27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>xxxxx</value>
      <webElementGuid>10c88fff-0ebe-47e7-b61a-502c784e8724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>3dd16de6-9908-4b21-8440-1d2aa5c3f64c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>39cc1ded-aa9f-4468-a3e9-700fdbb8293c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>sentences</value>
      <webElementGuid>aab7ce5e-3bc1-4cf8-9336-63f6605f968f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>2f6db8d2-e70d-4927-9559-fa890f153b93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>ae5748ae-5287-4d2f-ad72-03f626ecd970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2a3559de-7e9a-4814-ab97-96b0bf95d34e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>00c75e42-1d63-41b3-ad89-3d9f80e6c80a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-focusable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c932735c-0ca3-4529-8bd3-adf4962ff8e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rn-97bpaa rn-n1uzsy rn-14lw9ot rn-hxd557 rn-69jxje rn-18wd4mo rn-r0sxug rn-ou6ah9 rn-t12b5v rn-zmljjp rn-pm2fo rn-1efd50x rn-14skgim rn-rull8r rn-mm0ijv rn-5kkj8d rn-13l2t4g rn-qklmqi rn-1ljd8xs rn-deolkf rn-14xgk7a rn-1b43r93 rn-1exrs8c rn-m611by rn-1qfoi16 rn-1mi0q7o rn-1hfyk0a rn-1ms1frn rn-1dz5y72</value>
      <webElementGuid>d407d978-a79c-4d03-a0db-bce41a4c2b57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;purchaserZipCode&quot;)</value>
      <webElementGuid>cfee45a0-13e7-49c4-a8c5-a4791cd8cf43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='purchaserZipCode']</value>
      <webElementGuid>0b08479d-c745-4858-8a81-c55262696ade</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/div/div/div/div/div[2]/div/div/div/div/div/div[5]/div[3]/div/div/div[2]/input</value>
      <webElementGuid>75f31a38-c837-4205-99ec-7ae961af6209</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[3]/div/div/div[2]/input</value>
      <webElementGuid>66cbd4c9-2c9b-4b0e-a75a-7bb9ab85cb87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'purchaserZipCode' and @id = 'purchaserZipCode' and @placeholder = 'xxxxx' and @type = 'number']</value>
      <webElementGuid>c2777837-e20d-48f4-8ddd-9fbb322eb853</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
