<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>katalon-div_id(katalon-rec_elementInfoDiv) (1)</name>
   <tag></tag>
   <elementGuidId>2d6ceaeb-27c5-4caf-a1f3-5f31b8e42d59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#katalon-rec_elementInfoDiv</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//katalon-div[@id='katalon-rec_elementInfoDiv']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>katalon-div</value>
      <webElementGuid>4251dd18-9782-4774-bb93-81ef1f66b356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>katalon-rec_elementInfoDiv</value>
      <webElementGuid>f0bf213b-0cf9-4c7b-8657-ab98d6eeffd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>id(&quot;katalon-rec_elementInfoDiv&quot;)</value>
      <webElementGuid>e2820d93-8bc9-4a36-b98b-26a846da942d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;katalon-rec_elementInfoDiv&quot;)</value>
      <webElementGuid>8e09dadd-e350-4491-aba4-7ff3f10effca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Tickets/iframe____privateStripeFrame22225</value>
      <webElementGuid>5a2c07a9-ec6b-4d53-aa4a-5a4f4efdc7ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//katalon-div[@id='katalon-rec_elementInfoDiv']</value>
      <webElementGuid>7cf583c5-c613-4118-a0e9-34ce59e6f773</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//katalon-div[@id='katalon']/katalon-div</value>
      <webElementGuid>ccb0d502-f459-4154-b615-c01c0a574d8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Number'])[1]/following::katalon-div[2]</value>
      <webElementGuid>3d7bc830-4627-44d1-846e-5480538329e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='id(&quot;katalon-rec_elementInfoDiv&quot;)']/parent::*</value>
      <webElementGuid>481332ec-11ae-4604-aef2-1e17c5f377b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//katalon-div/katalon-div</value>
      <webElementGuid>7692efbf-c5da-4427-86da-edfb1dd64192</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//katalon-div[@id = 'katalon-rec_elementInfoDiv' and (text() = 'id(&quot;katalon-rec_elementInfoDiv&quot;)' or . = 'id(&quot;katalon-rec_elementInfoDiv&quot;)')]</value>
      <webElementGuid>4fef29fa-7182-47fe-a670-d5ad9e1f9abd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
