<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__purchaserZipCode</name>
   <tag></tag>
   <elementGuidId>6050ac63-c814-41df-a71d-db2bff326b6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#purchaserZipCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='purchaserZipCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a2d67fdf-c12d-4052-8649-5f1ce05c1efe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>purchaserZipCode</value>
      <webElementGuid>d027e750-a057-4eba-a904-b85fbb9f47cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>purchaserZipCode</value>
      <webElementGuid>30d84490-7bd2-494c-ac46-add3de98488d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Billing Zip Code</value>
      <webElementGuid>d4bc0b54-b953-46bd-8f32-4105f198dff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>xxxxx</value>
      <webElementGuid>f8dbd8b2-def4-43a4-8897-b25724890f53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>03ff4b05-8b57-4570-ad5a-dd2b13eb18cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>9e481226-fd4d-4fc5-af86-8654d5d3e963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>sentences</value>
      <webElementGuid>f65d7b4f-6033-426a-9bb2-fb78f27baa52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>e37a4758-8a15-4db0-9929-360ef607c18e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>95d4e280-920a-4114-94a0-722f63e14ed2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ad3f609a-4bc8-459d-9748-69a684bcf70b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>a4abe7a5-61e3-4d05-a63a-f3fa282dbf24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-focusable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ff0977b6-9e1e-480a-b19e-91d3cc34158b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rn-97bpaa rn-n1uzsy rn-14lw9ot rn-hxd557 rn-69jxje rn-18wd4mo rn-r0sxug rn-ou6ah9 rn-t12b5v rn-zmljjp rn-pm2fo rn-1efd50x rn-14skgim rn-rull8r rn-mm0ijv rn-5kkj8d rn-13l2t4g rn-qklmqi rn-1ljd8xs rn-deolkf rn-14xgk7a rn-1b43r93 rn-1exrs8c rn-m611by rn-1qfoi16 rn-1mi0q7o rn-1hfyk0a rn-1ms1frn rn-1dz5y72</value>
      <webElementGuid>aade0d65-8bdc-45f6-bddf-bd033784f931</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;purchaserZipCode&quot;)</value>
      <webElementGuid>350c80cb-02f1-45b3-9908-3b9d0fe89cca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='purchaserZipCode']</value>
      <webElementGuid>d7b3f906-adb1-48b6-9a11-a2d5fd47abc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/div/div/div/div/div[2]/div/div/div/div/div/div[5]/div[3]/div/div/div[2]/input</value>
      <webElementGuid>aea58b26-0a13-4ac9-bbbe-94120460a1b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[3]/div/div/div[2]/input</value>
      <webElementGuid>0b193ba5-eedc-4871-914a-55ce76845ac8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'purchaserZipCode' and @id = 'purchaserZipCode' and @placeholder = 'xxxxx' and @type = 'number']</value>
      <webElementGuid>bedd8c59-b077-4531-a525-bb604d6846cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
