<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SW Fee for Teams_teams_sw_fee</name>
   <tag></tag>
   <elementGuidId>2145d006-479c-4395-886c-fddf68743d7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;teams_sw_fee&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='teams_sw_fee']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dcd5d5b4-162a-41fd-8785-55d24cbb6590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>fcfc2b28-152e-493d-8afb-3dc4bd2cad22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>teams_sw_fee</value>
      <webElementGuid>3bc385de-0007-46ba-8b10-b0a48b46bf72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>$ctrl.event.teams_sw_fee</value>
      <webElementGuid>f4230914-a498-4261-b0d5-b158af8364dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-valid ng-not-empty ng-valid-min ng-valid-required ng-dirty ng-valid-number</value>
      <webElementGuid>7587c171-893d-4860-be34-0b18c8845d69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>44a74ed1-70ea-49a4-b3c8-e35ea2bfaaf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-js&quot;]/body[@class=&quot;modal-open&quot;]/div[@class=&quot;modal fade in&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/modal-wrapper[1]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12&quot;]/ng-transclude[1]/event-monetary-edit[1]/form[@class=&quot;form-horizontal ng-valid ng-valid-min ng-valid-required ng-dirty ng-valid-number&quot;]/div[@class=&quot;validation-required form-group&quot;]/div[@class=&quot;col-sm-4&quot;]/input[@class=&quot;form-control ng-untouched ng-valid ng-not-empty ng-valid-min ng-valid-required ng-dirty ng-valid-number&quot;]</value>
      <webElementGuid>d3940d8d-7f49-41b8-96d0-ca820cc551b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='teams_sw_fee']</value>
      <webElementGuid>e5070df4-a4bf-488e-a5bf-1bee05ed3f28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>faba5bc4-a655-4fd4-849e-5b55a96ac05f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'teams_sw_fee']</value>
      <webElementGuid>33d8b7e9-2c1b-4842-8d30-815ce1f51c9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
