<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Other Events_searchbox</name>
   <tag></tag>
   <elementGuidId>746644ac-ee22-45eb-b9de-b2c34d0b6ff4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='searchbox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;searchbox&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Search...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b453fa28-a6f3-4179-b3d4-78f8dc173f1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5b8dceea-f119-494e-8ff8-226903e7d68a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>searchbox</value>
      <webElementGuid>c2b19b37-2212-42cb-a61b-78e5fe43c656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control search_teams white-ro ng-empty</value>
      <webElementGuid>de6507d3-34d3-41f3-9db8-c5e42fcc4f4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search...</value>
      <webElementGuid>8d580e51-98d1-4a4a-b111-4af679ac36bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>$ctrl.inputModel</value>
      <webElementGuid>ccf505c6-fc4d-4d05-ba85-6942cbfe473e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-keyup</name>
      <type>Main</type>
      <value>$ctrl.onKeypress($event)</value>
      <webElementGuid>b1aad0ab-4bb2-4d06-96c8-b10fb452cae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-readonly</name>
      <type>Main</type>
      <value>$ctrl.isReadonly()</value>
      <webElementGuid>083f7e92-e861-41b8-81a2-9ed730016edb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-js&quot;]/body[1]/div[@class=&quot;container-fluid block-height-min&quot;]/div[1]/div[@class=&quot;tab-content&quot;]/div[@class=&quot;tab-pane active&quot;]/events-list[1]/div[@class=&quot;form-inline row-space&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;search-box search-input&quot;]/sw-searchbox[1]/div[@class=&quot;form-group--custom sw-searchbox&quot;]/div[@class=&quot;search-box&quot;]/input[@class=&quot;form-control search_teams white-ro ng-empty&quot;]</value>
      <webElementGuid>caec1740-c32c-4a88-bbc5-594c1df867bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='searchbox']</value>
      <webElementGuid>ddd15292-2768-466b-abf8-208547ef1b34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c70ef39d-fa70-4967-a111-2ece00c4a7cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'searchbox' and @placeholder = 'Search...']</value>
      <webElementGuid>6f097444-e87a-4d13-9b52-432e5261eb77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
