<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_CHECK (pending)</name>
   <tag></tag>
   <elementGuidId>cb7254a1-3197-4ece-876c-7c08267cdae6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='accordiongroup-1384-5049-tab']/h4/a/span/payment-info-accord-heading/span/b/span[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.text-info > b > span:nth-of-type(3)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;#16823306 - CHECK (pending) 04/14 9:41am Inv.: $3,000.00&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>dbc8eb23-2df4-41f4-ab54-669ea686c6a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CHECK (pending)</value>
      <webElementGuid>1aa150ca-b266-476a-bc8b-ae81954ae491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accordiongroup-1384-5049-tab&quot;)/h4[@class=&quot;panel-title&quot;]/a[@class=&quot;accordion-toggle&quot;]/span[1]/payment-info-accord-heading[1]/span[@class=&quot;text-info&quot;]/b[1]/span[3]</value>
      <webElementGuid>b28892a6-7282-4ed0-9c42-5f84cf7bb868</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordiongroup-1384-5049-tab']/h4/a/span/payment-info-accord-heading/span/b/span[3]</value>
      <webElementGuid>b737fc12-61b0-4ad8-8ed3-f5cfdc222218</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[4]/following::span[1]</value>
      <webElementGuid>16a95d96-20ad-4310-a68d-c7488860b097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#16823306'])[1]/following::span[2]</value>
      <webElementGuid>e23ab072-ab71-4f7a-9218-6d23afb88096</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inv.:'])[1]/preceding::span[3]</value>
      <webElementGuid>57ed8ac6-18c5-4b2c-8929-249fa408e78e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CHECK (pending)']/parent::*</value>
      <webElementGuid>3d229dfa-1d27-4f82-977f-9653dc05b484</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/h4/a/span/payment-info-accord-heading/span/b/span[3]</value>
      <webElementGuid>63ac64c3-74d4-455f-9919-91072552f492</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'CHECK (pending)' or . = 'CHECK (pending)')]</value>
      <webElementGuid>88efe72a-1eb7-47ec-99ac-fcb1f60d408f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
