<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__purchaserLast</name>
   <tag></tag>
   <elementGuidId>45a69547-6585-4883-baef-f0212c37d003</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='purchaserLast']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#purchaserLast</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d8105b93-abeb-4685-adf2-7a6be687c378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>purchaserLast</value>
      <webElementGuid>fdf87400-9f00-4efc-9cb2-0d4fd4592396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>purchaserLast</value>
      <webElementGuid>3a303b76-597a-4df7-8470-4ac38ae506a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Last Name</value>
      <webElementGuid>faef7edb-d32f-40db-a7a7-3d6a591b9f18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Last</value>
      <webElementGuid>4fc7482d-02f4-44c0-9cce-9c15ec37a1b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>0d36902f-14ea-463d-be4b-d7e19607e1ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>sentences</value>
      <webElementGuid>2104b247-a6aa-4726-aeb9-a28ab41c63b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>dfaed16c-ab41-46cd-a0c0-0264c67b184f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>3b828379-f3b0-43ef-9b4c-ff5eef748f64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7623e9c9-80e5-483c-937e-e59bba2530e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>27dbba6d-61db-45a5-b370-95e7fd22519d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-focusable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6e9e0cd3-4da9-4c27-ba64-bba73fce14a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rn-97bpaa rn-n1uzsy rn-14lw9ot rn-hxd557 rn-69jxje rn-18wd4mo rn-r0sxug rn-ou6ah9 rn-t12b5v rn-zmljjp rn-pm2fo rn-1efd50x rn-14skgim rn-rull8r rn-mm0ijv rn-5kkj8d rn-13l2t4g rn-qklmqi rn-1ljd8xs rn-deolkf rn-14xgk7a rn-1b43r93 rn-1exrs8c rn-m611by rn-1qfoi16 rn-1mi0q7o rn-1hfyk0a rn-1ms1frn rn-1dz5y72</value>
      <webElementGuid>8e329551-4698-474e-8b49-01feecf41615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;purchaserLast&quot;)</value>
      <webElementGuid>06267637-9ff2-41ae-be04-fd534d34f8b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='purchaserLast']</value>
      <webElementGuid>b319cc4a-4d2c-4784-b746-982589721f14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/div/div/div/div/div[2]/div/div/div/div/div/div[3]/div[3]/div/div/div[2]/input</value>
      <webElementGuid>0fa10193-8c38-497b-9b41-00d949436d03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/input</value>
      <webElementGuid>3b49c834-0c27-4d7b-9afb-53db00a336c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'purchaserLast' and @id = 'purchaserLast' and @placeholder = 'Last' and @type = 'text']</value>
      <webElementGuid>3bd72346-8961-4ac9-a6de-dab7a8cb7649</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
