<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Teams</name>
   <tag></tag>
   <elementGuidId>96f98ed2-6f1d-4e27-9936-3e28ce01c3b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Teams')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0e1dfe86-5944-49fc-824d-22d4ac03e351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>$ctrl.showTeamsTab(event)</value>
      <webElementGuid>bdcbfff8-9a7a-4ad7-9067-26d20ad22b23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ui-state</name>
      <type>Main</type>
      <value>$ctrl.data.teams_state</value>
      <webElementGuid>a00ffe30-698e-4506-8ff2-a86793002264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ui-state-params</name>
      <type>Main</type>
      <value>{ event: event.event_id }</value>
      <webElementGuid>971576c1-16b0-4328-8a26-85bf49f673eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-success</value>
      <webElementGuid>782262fa-8179-46a8-8d21-9e117f977f6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#/event/25522/allteams</value>
      <webElementGuid>1ffbe05b-3cae-4113-9627-352067ea711d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Teams </value>
      <webElementGuid>37f3d8c8-947b-4ead-a792-bac018dfd3a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-js&quot;]/body[1]/div[@class=&quot;container-fluid block-height-min&quot;]/div[1]/div[@class=&quot;tab-content&quot;]/div[@class=&quot;tab-pane active&quot;]/events-list[1]/div[@class=&quot;table-responsive data-loading done&quot;]/table[@class=&quot;table sw-adaptive-grid text-center&quot;]/tbody[1]/tr[@class=&quot;text-bold&quot;]/td[@class=&quot;td--135&quot;]/div[2]/small[1]/a[@class=&quot;text-success&quot;]</value>
      <webElementGuid>8bf3d5bc-b99b-4c33-aced-dd8026f7f23e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Teams')]</value>
      <webElementGuid>d939af0d-8371-45ca-bd1e-dcbed6870d8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Divisions'])[1]/following::a[1]</value>
      <webElementGuid>c3d0ee82-0f2b-4b7f-875b-36035b0d9f7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TE'])[1]/following::a[2]</value>
      <webElementGuid>0da58443-628c-492b-b71d-b88d9d51cbb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tickets'])[3]/preceding::a[1]</value>
      <webElementGuid>37a4faf8-6e83-46e2-a1af-09418ecb2bbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$1000'])[1]/preceding::a[2]</value>
      <webElementGuid>04b764c7-57f4-49b7-8f17-db599c4e6343</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Teams']/parent::*</value>
      <webElementGuid>10f2ff5a-f791-4886-9e9a-561a916f88d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#/event/25522/allteams')]</value>
      <webElementGuid>dfd503f4-1948-4398-82bf-ce9ffae78c34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//small/a[2]</value>
      <webElementGuid>a394bfeb-8a9f-4417-9ba5-6bdb8ce05ff9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#/event/25522/allteams' and (text() = 'Teams ' or . = 'Teams ')]</value>
      <webElementGuid>8b0cdc54-afd6-4fee-9ca5-8b4fae6da2d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
