<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_coed_input-inline ng-pristine ng-unto_3df5b0_1</name>
   <tag></tag>
   <elementGuidId>3911fe67-26de-42c6-a2f4-6986dd1f12d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.pointer > input.input-inline.ng-pristine.ng-untouched.ng-valid.ng-empty</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='checkbox'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>19dd8610-6297-4d45-886a-17769392d486</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>bdd34856-b0c6-4486-b80d-31c895e04a3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-inline ng-pristine ng-untouched ng-valid ng-empty</value>
      <webElementGuid>3baac661-0c1a-4cd0-9a48-a10f4b8f6381</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>selection[age.age]</value>
      <webElementGuid>99233327-f86c-42ce-b80b-178a3503ad50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>dataChanged()</value>
      <webElementGuid>0a44f56e-66ce-422e-b2ab-31d6b5c7cb88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-js&quot;]/body[@class=&quot;modal-open&quot;]/div[@class=&quot;modal fade in&quot;]/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/divisions-wirard[1]/form[@class=&quot;form-horizontal row-space ng-valid ng-valid-maxlength ng-dirty ng-valid-parse&quot;]/div[@class=&quot;row rowm0&quot;]/div[@class=&quot;col-xs-3 divisions--border&quot;]/wizard-ages[1]/div[@class=&quot;row row-space--small age-row&quot;]/div[@class=&quot;col-xs-6&quot;]/label[@class=&quot;pointer&quot;]/input[@class=&quot;input-inline ng-pristine ng-untouched ng-valid ng-empty&quot;]</value>
      <webElementGuid>9d79fe8a-3c0c-4aef-8ac1-8e5ac423715b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='checkbox'])[5]</value>
      <webElementGuid>f980cb90-80d8-471c-a5a2-8c09d6df613c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/label/input</value>
      <webElementGuid>7551f0f2-0735-47a0-a47a-559f99e10042</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>129b0f4d-50a4-4289-9042-21698a86485f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
