<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_card_holder_name-491-644-09f</name>
   <tag></tag>
   <elementGuidId>93f9d4ed-0a82-4fd1-8fca-a1043556417f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='billing-info']/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#payment-element-wrapper > #payment-form > #billing-info > div.form-control > #card-holder-name</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @id = 'card-holder-name' and @name = 'card_holder_name' and @placeholder = 'Full Name' and @ref_element = 'Object Repository/Insurance purchase/Page_Tickets/payment-element-ets-491-644' and @ref_element_is_shadow_root = 'true']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9852443d-c9f5-4719-a626-159951488d24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>beee368d-7db8-4c1b-afcc-958a8b7c1176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>card-holder-name</value>
      <webElementGuid>f0ce2fca-8e88-4339-a3d2-aab5adbea060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>card_holder_name</value>
      <webElementGuid>c165d7ba-1bbd-4fd3-a555-f3f09e44160f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Full Name</value>
      <webElementGuid>eca90b23-e519-4a0a-8a74-c0e069f1828b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@id=&quot;payment-element-wrapper&quot;]/section[@id=&quot;payment-form&quot;]/section[@id=&quot;billing-info&quot;]/div[@class=&quot;form-control&quot;]/input[@id=&quot;card-holder-name&quot;]</value>
      <webElementGuid>04eaf86c-2768-48de-80ad-3eb49a282b4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Insurance purchase/Page_Tickets/payment-element-ets-491-644</value>
      <webElementGuid>e6d9af23-7040-470b-85e8-7b089cc33831</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f74bd784-9568-42ca-8d24-25105c0bf98a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='billing-info']/div/input</value>
      <webElementGuid>981ccf97-5014-4f0c-82d1-269412b81688</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'card-holder-name' and @name = 'card_holder_name' and @placeholder = 'Full Name']</value>
      <webElementGuid>32850e9d-ff4b-4e17-9108-4609185f9147</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
