<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ticket-refund-Tickets-491</name>
   <tag></tag>
   <elementGuidId>033b2702-62db-4c24-8c9e-2f2f1ee0abcf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='vertical-insurance-container']/ticket-refund</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;vertical-insurance-container&quot;)/ticket-refund[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ticket-refund</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ticket-refund</value>
      <webElementGuid>43410ded-016e-4d4d-b193-ebe33d2e060c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>selected-state</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>0163c0ae-4f27-41ea-ae21-a67c5d72ef63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vertical-insurance-container&quot;)/ticket-refund[1]</value>
      <webElementGuid>70f12631-17ed-4cc3-b836-dfd7f5ae02af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vertical-insurance-container']/ticket-refund</value>
      <webElementGuid>874d5d56-d3d7-47f2-ba62-099222768109</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ticket-refund</value>
      <webElementGuid>29245bb2-fec6-4a93-af03-764e6fa567c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
