<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_11111</name>
   <tag></tag>
   <elementGuidId>44a63ed4-5fad-4a9a-9f56-b6629b6fd8e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Zip Code:'])[1]/following::div[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cfcf1f83-5330-4a28-85d1-10a5073321bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>receipt_participant_information-body_item-value</value>
      <webElementGuid>2dd2f435-5c6f-4ce5-8ceb-971653394968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>11111</value>
      <webElementGuid>cf0376e6-3969-43e1-8c33-654054a08b6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;receipt_wrapper&quot;]/div[@class=&quot;receipt_participant&quot;]/div[@class=&quot;receipt_participant_information&quot;]/div[@class=&quot;receipt_participant_information-body&quot;]/div[@class=&quot;receipt_participant_information-body_item&quot;]/div[@class=&quot;receipt_participant_information-body_item-value&quot;]</value>
      <webElementGuid>2cea38a1-09d4-478a-b971-a214175313ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zip Code:'])[1]/following::div[1]</value>
      <webElementGuid>99c9f50b-955f-41ca-9a96-5e9e0ecd9875</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(111) 111-11111'])[1]/following::div[3]</value>
      <webElementGuid>81e48901-bce3-4096-9945-f3c940d23989</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Purchased:'])[1]/preceding::div[1]</value>
      <webElementGuid>b5df8e28-01c9-400e-ba78-3de0288baad2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='May 11, 2025, 05:37 PM'])[1]/preceding::div[2]</value>
      <webElementGuid>4d517c97-462c-4004-b6b9-21255b06fb9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='11111']/parent::*</value>
      <webElementGuid>6864b88f-594b-425a-8cfd-620e815850fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]</value>
      <webElementGuid>875a22f7-b214-4471-8b37-8b225b8eca8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '11111' or . = '11111')]</value>
      <webElementGuid>62806294-52f5-4cc2-bf75-2ebbf6f91ce0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
