<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ACH (paid)_1</name>
   <tag></tag>
   <elementGuidId>f7911c46-9ab5-4ebe-998e-7794a3fe4a5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='accordiongroup-12065-4139-tab']/h4/a/span/payment-info-accord-heading/span/b/span[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>b > span:nth-of-type(3)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;#16823295 - ACH (paid) 04/14 8:59am $1,500.00 Ref.: $2,500.00 (04/14)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6d226e99-371c-4b8b-83a7-38bc79a6bcb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ACH (paid)</value>
      <webElementGuid>79fa0dc1-a45f-4bdc-b5b7-3b061b1fc960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accordiongroup-12065-4139-tab&quot;)/h4[@class=&quot;panel-title&quot;]/a[@class=&quot;accordion-toggle&quot;]/span[1]/payment-info-accord-heading[1]/span[@class=&quot;text-success&quot;]/b[1]/span[3]</value>
      <webElementGuid>8542f530-6548-47ec-bef1-a0708aa3541d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordiongroup-12065-4139-tab']/h4/a/span/payment-info-accord-heading/span/b/span[3]</value>
      <webElementGuid>1d2fbf0c-44ab-4c20-ae9e-487125f16de3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/following::span[1]</value>
      <webElementGuid>537e81b7-fff9-40fc-aaf5-8c483f401b59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#16823295'])[1]/following::span[2]</value>
      <webElementGuid>fd345946-1279-43c3-83ca-f50850f01c16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$1,500.00'])[1]/preceding::span[3]</value>
      <webElementGuid>7950422a-c5f4-414f-b07d-9d5a2e0e89df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ACH (paid)']/parent::*</value>
      <webElementGuid>83c2c684-fadb-4a35-893a-5876e7aaf91b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//b/span[3]</value>
      <webElementGuid>0e9feb6f-e64b-4886-a8d3-61a56cd12e5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'ACH (paid)' or . = 'ACH (paid)')]</value>
      <webElementGuid>64604346-d115-4aa6-9588-b1522320de02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
