<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Import New AthleteStaff and Update Cu_a5a4d5</name>
   <tag></tag>
   <elementGuidId>c9ad92af-decd-418e-8f09-42b66f9f9aaa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='import_option'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Import New Athlete/Staff and Update Current Athlete/Staff:I want to update the list of currently available athletes and staff by importing members from SportEngine that are not currently in SportWrench. I also want to update the current athlete/staff in SportWrench with values from SportEngine (i.e, update uniform number and/or team). New athletes/staff will be added to existing event rosters and updated athlete/staff values will be added to existing rosters.THIS WILL REPLACE INFORMATION IN SPORTWRENCH WITH SPORTENGINE DATA IF IT EXISTS&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>db9c48ac-b450-4723-a449-d214b510607e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>aa73fec9-2875-471f-8c6a-6f4a95a287a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>import_option</value>
      <webElementGuid>dee68a15-cb6e-4eba-adea-921019e34273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>$ctrl.importData.option</value>
      <webElementGuid>112ebb4c-d26d-4590-bad8-2fd366a75891</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>2a4053ee-d2ae-46ac-9b00-57f27b3c06cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid ng-not-empty</value>
      <webElementGuid>1c56e437-077e-49c0-985b-e1f763b2b509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-js&quot;]/body[@class=&quot;modal-open&quot;]/div[@class=&quot;modal fade in&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/sport-engine-import[1]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12&quot;]/form[@class=&quot;form-horizontal row-space ng-pristine ng-valid&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;well col-sm-offset-1 col-sm-10&quot;]/label[@class=&quot;col-sm-offset-1 radio&quot;]/input[@class=&quot;ng-pristine ng-untouched ng-valid ng-not-empty&quot;]</value>
      <webElementGuid>09a38049-104d-466b-ab86-889020762111</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='import_option'])[2]</value>
      <webElementGuid>a19546a6-57b9-49f9-a66a-e60f093ba5fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/input</value>
      <webElementGuid>70c68cde-d7c9-4a88-999f-1f3d32c1fc36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'import_option']</value>
      <webElementGuid>af86e94b-ec44-464a-8af7-5f87d46c1a5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
