<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Received_is_received</name>
   <tag></tag>
   <elementGuidId>a846b48a-acfd-470d-a39a-4979ba918695</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='is_received']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;is_received&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Received&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>18c0aaff-1474-4f03-b76b-8418ff11681e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>680db71a-7c8b-4b90-afeb-65c51d9247f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>is_received</value>
      <webElementGuid>ed587112-811d-4c6f-8120-e85caf31435d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>$ctrl.enableCheckForm</value>
      <webElementGuid>556515c2-1cab-4582-9e49-6b55c37a3ac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>$ctrl.receivedPickerToggle()</value>
      <webElementGuid>1a3b8af8-d02c-499b-ace1-03a79d73216c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid ng-empty</value>
      <webElementGuid>4604dd0a-152f-41d3-b333-8411ee81ccb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accordiongroup-2090-6463-panel&quot;)/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row&quot;]/receive-check-form[1]/form[@class=&quot;form-inline row-space receive-check-form ng-pristine ng-valid-date ng-invalid ng-invalid-required ng-valid-maxlength ng-valid-greater-than-zero&quot;]/div[@class=&quot;form-group&quot;]/label[@class=&quot;checkbox pointer&quot;]/input[@class=&quot;ng-pristine ng-untouched ng-valid ng-empty&quot;]</value>
      <webElementGuid>2c868667-9006-4c06-852d-a5f287c1b3d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='is_received']</value>
      <webElementGuid>85ac826c-4787-452a-bca6-c32bfbc0321f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordiongroup-2090-6463-panel']/div/div/receive-check-form/form/div/label/input</value>
      <webElementGuid>51d41aec-b57b-496a-8c71-4551590545fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>0b40874d-c49c-42ab-9a87-cdf752c00590</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'is_received']</value>
      <webElementGuid>c87c25e9-bd37-47f7-aac8-dec3c647117d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
